#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_system_configuration_viewer_html.py

E/E Architect Design v4 generic system JSON viewer and ECU I/O sizing tool.

Input:
  - one eec-system JSON file, or
  - a directory/glob containing multiple system JSON files generated by the JSON generator.

Output:
  - standalone HTML app with graphical system view, hover/click detail panel,
    per-system ECU I/O demand, and multi-system reservation sizing.

Important sizing modes:
  - Single system: exact I/O need for the selected system.
  - Alternative selection: user selects several systems, but only one is mounted at a time;
    required reserved pins = bucket-wise maximum across selected systems.
  - Cumulative selection: comparison mode for systems mounted together; required pins = sum.

No third-party Python package is required. The generated HTML is self-contained.
"""
from __future__ import annotations

import argparse
import csv
import fnmatch
import json
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from html import escape as hesc
from pathlib import Path
from typing import Any, Iterable

SCRIPT_NAME = "generate_system_configuration_viewer_html.py"
CONFIG_FILE = "eec_system_viewer_config.v4.json"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_CONFIG: dict[str, Any] = {
    "title": "E/E Architect Design — System Configuration & ECU I/O Viewer",
    "output_dir": "generated_doc/system_viewer",
    "output_html": "index.html",
    "input_candidates": ["library/systems", "systems", "."],
    "include_globs": ["*.json", "*.eec-system-*.json", "*.shared.json", "*.generator.json"],
    "exclude_globs": ["*.bak", "*.patch", "manifest.json", "*summary*.json", "*report*.json", "*validation*.json"],
    "system_type_tokens": ["system", "eec-system"],
    "component_keys": ["components"],
    "top_level_device_keys": ["devices", "sensors", "actuators"],
    "component_device_keys": ["devices", "sensors", "actuators"],
    "signal_name_keys": ["name", "prefix", "id", "signal"],
    "pin_number_keys": ["number", "pin_number", "physical_number", "cavity"],
    "pin_interface_keys": ["interface_type", "interface", "type"],
    "signal_interface_keys": ["interface", "interface_type", "type"],
    "signal_role_keys": ["role"],
    "bus_interfaces": ["CAN", "LIN", "ETHERNET", "FLEXRAY", "ISOBUS"],
    "electrical_flags": {
        "1": "PULLUP", "2": "PULLDOWN", "4": "HIGH_SIDE", "8": "LOW_SIDE",
        "16": "PUSH_PULL", "32": "CURRENT_SENSE", "64": "VOLTAGE_IN", "128": "DIFFERENTIAL"
    },
    "diagnostic_flags": {
        "1": "OPEN_LOAD", "2": "SHORT_GND", "4": "SHORT_BAT", "8": "RANGE_CHECK",
        "16": "OVERCURRENT", "32": "THERMAL_WARN", "64": "LINE_BREAK", "128": "PLAUSIBILITY"
    },
    "io_categories": [
        {"code": "AI", "label": "Analog inputs", "description": "Analog voltage input pins to reserve on ECU"},
        {"code": "DI", "label": "Digital inputs", "description": "Digital input pins to reserve on ECU"},
        {"code": "FI", "label": "Frequency inputs", "description": "Frequency / speed input pins"},
        {"code": "SENT", "label": "SENT inputs", "description": "SENT sensor interfaces"},
        {"code": "CURR", "label": "Current inputs", "description": "Current / 4–20 mA analog current input pins"},
        {"code": "RES", "label": "Resistance inputs", "description": "Resistive / NTC / RTD input pins"},
        {"code": "TEMP", "label": "Temperature inputs", "description": "Temperature-class input pins"},
        {"code": "PWM", "label": "PWM outputs", "description": "PWM output pins"},
        {"code": "PWM_HS", "label": "PWM high-side outputs", "description": "PWM high-side output pins"},
        {"code": "PWM_LS", "label": "PWM low-side outputs", "description": "PWM low-side output pins"},
        {"code": "DO", "label": "Digital outputs", "description": "Digital output pins"},
        {"code": "DO_HS", "label": "Digital high-side outputs", "description": "Static high-side output pins"},
        {"code": "DO_LS", "label": "Digital low-side outputs", "description": "Static low-side output pins"},
        {"code": "CAN", "label": "CAN channels", "description": "CAN bus channels/interfaces"},
        {"code": "LIN", "label": "LIN channels", "description": "LIN bus channels/interfaces"},
        {"code": "ETH", "label": "Ethernet channels", "description": "Ethernet/100BASE-T1 channels"},
        {"code": "SUP", "label": "Supply pins", "description": "Battery / ignition / protected supply pins"},
        {"code": "SENS_SUP", "label": "Sensor supply pins", "description": "Sensor supply / reference voltage pins"},
        {"code": "GND", "label": "Ground pins", "description": "Power/signal ground pins"},
        {"code": "INOUT", "label": "Bidirectional channels", "description": "Generic bidirectional I/O"},
        {"code": "OTHER", "label": "Other I/O", "description": "Other or unknown pin classes"}
    ]
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def deep_update(base: dict[str, Any], over: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_update(out[k], v)
        else:
            out[k] = v
    return out


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def esc(value: Any) -> str:
    return hesc(str("" if value is None else value), quote=True)


def as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def to_int(value: Any, default: int = 0) -> int:
    if isinstance(value, bool):
        return default
    try:
        return int(value)
    except Exception:
        return default


def to_float(value: Any, default: float = 0.0) -> float:
    if isinstance(value, bool):
        return default
    try:
        return float(value)
    except Exception:
        return default


def clean_id(value: Any) -> str:
    text = str(value or "item").strip()
    text = re.sub(r"[^A-Za-z0-9_\-]+", "_", text)
    return text.strip("_") or "item"


def best_str(obj: dict[str, Any], keys: Iterable[str], default: str = "") -> str:
    for key in keys:
        val = obj.get(key)
        if isinstance(val, str) and val.strip():
            return val.strip()
        if val is not None and not isinstance(val, (dict, list)):
            return str(val)
    return default


def unique(items: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item and item not in seen:
            out.append(item)
            seen.add(item)
    return out


def load_config(path: Path | None) -> dict[str, Any]:
    cfg = dict(DEFAULT_CONFIG)
    if path and path.exists():
        data = read_json(path)
        if isinstance(data, dict):
            cfg = deep_update(cfg, data)
    # derived lookup
    cfg["_category_by_code"] = {str(c["code"]): c for c in cfg.get("io_categories", []) if isinstance(c, dict) and c.get("code")}
    cfg["_category_order"] = [str(c["code"]) for c in cfg.get("io_categories", []) if isinstance(c, dict) and c.get("code")]
    return cfg


def matches_any(path: Path, patterns: list[str]) -> bool:
    name = path.name
    rel = str(path).replace("\\", "/")
    return any(fnmatch.fnmatch(name, pat) or fnmatch.fnmatch(rel, pat) for pat in patterns)


def discover_files(root: Path, raw_input: str | None, cfg: dict[str, Any]) -> list[Path]:
    candidates: list[Path] = []
    if raw_input:
        raw = Path(raw_input)
        if not raw.is_absolute():
            raw = root / raw
        s = str(raw)
        if any(ch in s for ch in "*?[]"):
            if s.startswith(str(root)):
                candidates = sorted(root.glob(str(raw.relative_to(root))))
            else:
                candidates = sorted(Path().glob(s))
        elif raw.is_file():
            candidates = [raw]
        elif raw.is_dir():
            candidates = sorted(raw.rglob("*.json"))
        else:
            raise FileNotFoundError(f"input path not found: {raw}")
    else:
        for cand in cfg.get("input_candidates", []):
            p = Path(cand)
            if not p.is_absolute():
                p = root / p
            if p.is_file():
                candidates.append(p)
            elif p.is_dir():
                candidates.extend(sorted(p.rglob("*.json")))
    include = list(cfg.get("include_globs", ["*.json"]))
    exclude = list(cfg.get("exclude_globs", []))
    out: list[Path] = []
    seen: set[Path] = set()
    for p in candidates:
        p = p.resolve()
        if p in seen or not p.exists() or not p.is_file():
            continue
        if include and not matches_any(p, include):
            continue
        if exclude and matches_any(p, exclude):
            continue
        out.append(p)
        seen.add(p)
    return sorted(out)


def looks_like_system(data: Any, cfg: dict[str, Any]) -> bool:
    if not isinstance(data, dict):
        return False
    typ = str(data.get("type", data.get("schema", ""))).lower()
    schema = str(data.get("schema_version", data.get("schema", ""))).lower()
    tokens = {str(t).lower() for t in cfg.get("system_type_tokens", [])}
    if typ in tokens or "eec-system" in schema:
        return True
    if data.get("name") and any(k in data for k in ("devices", "components", "sensors", "actuators")):
        return True
    return False


def norm_device_type(dev: dict[str, Any], hint: str = "") -> str:
    raw = best_str(dev, ["device_type", "type", "kind"], "").upper()
    if raw in {"SENSOR", "ACTUATOR"}:
        return raw
    h = hint.lower()
    if h.startswith("sensor"):
        return "SENSOR"
    if h.startswith("actuator"):
        return "ACTUATOR"
    if "drive_topology" in dev or "actuator_template" in dev:
        return "ACTUATOR"
    if "sensor_template" in dev:
        return "SENSOR"
    return raw or "DEVICE"


def collect_devices(raw: dict[str, Any], cfg: dict[str, Any]) -> list[dict[str, Any]]:
    devices: list[dict[str, Any]] = []

    def add(item: Any, hint: str, component: dict[str, Any] | None = None) -> None:
        if not isinstance(item, dict):
            return
        dev = dict(item)
        dev["_viewer_device_type"] = norm_device_type(dev, hint)
        if component:
            dev["_viewer_component_name"] = str(component.get("name", ""))
            dev["_viewer_component"] = {k: v for k, v in component.items() if k not in ("devices", "sensors", "actuators")}
        devices.append(dev)

    for key in cfg.get("top_level_device_keys", []):
        for dev in as_list(raw.get(key)):
            add(dev, key)

    for comp_key in cfg.get("component_keys", []):
        comps = raw.get(comp_key)
        if not isinstance(comps, list):
            continue
        for comp in comps:
            if not isinstance(comp, dict):
                continue
            for key in cfg.get("component_device_keys", []):
                for dev in as_list(comp.get(key)):
                    add(dev, key, comp)
    return devices


def signal_id(sig: dict[str, Any], cfg: dict[str, Any]) -> str:
    return best_str(sig, cfg.get("signal_name_keys", []), "")


def expanded_signal_names(sig: dict[str, Any], cfg: dict[str, Any]) -> list[str]:
    base = signal_id(sig, cfg)
    count = max(1, to_int(sig.get("count", 1), 1))
    if not base:
        return []
    if count == 1:
        return [base]
    return [f"{base}_{i+1:02d}" for i in range(count)]


def build_signal_index(signals: list[dict[str, Any]], cfg: dict[str, Any]) -> dict[str, dict[str, Any]]:
    idx: dict[str, dict[str, Any]] = {}
    for sig in signals:
        if not isinstance(sig, dict):
            continue
        ids: list[str] = []
        for key in cfg.get("signal_name_keys", []):
            v = sig.get(key)
            if isinstance(v, str) and v.strip():
                ids.append(v.strip())
        ids.extend(expanded_signal_names(sig, cfg))
        for item in unique(ids):
            idx[item] = sig
    return idx


def decode_bitmask(value: Any, labels: dict[str, str]) -> list[str]:
    val = to_int(value, 0)
    out: list[str] = []
    for bit_s, name in labels.items():
        bit = to_int(bit_s, 0)
        if bit and (val & bit):
            out.append(str(name))
    return out


def infer_flags_from_text(*parts: Any) -> list[str]:
    txt = " ".join(str(p or "") for p in parts).upper().replace("-", "_")
    flags: list[str] = []
    if any(t in txt for t in ("HIGH_SIDE", "HIGHSIDE", "HS_", "_HS", "DOH", "PDOH", "POH")):
        flags.append("HIGH_SIDE")
    if any(t in txt for t in ("LOW_SIDE", "LOWSIDE", "LS_", "_LS", "DOL", "PDOL")):
        flags.append("LOW_SIDE")
    if any(t in txt for t in ("CURRENT_SENSE", "CURR_SENSE", "CS", "CURRENT SENSE")):
        flags.append("CURRENT_SENSE")
    if "PUSH_PULL" in txt or "PUSH PULL" in txt:
        flags.append("PUSH_PULL")
    return unique(flags)


def signal_ref_from_pin(pin: dict[str, Any], cfg: dict[str, Any]) -> str:
    sig = pin.get("signal")
    if isinstance(sig, dict):
        return signal_id(sig, cfg)
    if isinstance(sig, str):
        return sig
    for key in ("signal_name", "signal_id", "signal_prefix", "net", "net_name"):
        if isinstance(pin.get(key), str) and pin.get(key).strip():
            return pin[key].strip()
    return ""


def get_interface(obj: dict[str, Any], keys: Iterable[str]) -> str:
    return best_str(obj, keys, "").upper()


def get_role(obj: dict[str, Any], keys: Iterable[str] = ("role",)) -> str:
    return best_str(obj, keys, "").upper()


def classify_io(device_type: str, role: str, interface: str, flags: list[str], cfg: dict[str, Any]) -> tuple[str, str]:
    """Return (io_code, ecu_direction) for one device endpoint/pin.

    device role is interpreted from the device point of view:
      sensor OUTPUT => ECU input
      actuator INPUT => ECU output
    """
    dt = (device_type or "").upper()
    role = (role or "").upper()
    iface = (interface or "UNKNOWN").upper()
    flags_u = {f.upper() for f in flags}
    bus = {str(x).upper() for x in cfg.get("bus_interfaces", [])}

    if role == "GROUND" or iface == "GROUND":
        return "GND", "GROUND"
    if role == "SUPPLY" or iface in {"POWER", "SUPPLY", "IGNITION"}:
        return "SUP", "SUPPLY"
    if iface == "SENSOR_SUPPLY":
        return "SENS_SUP", "SUPPLY"
    if role == "INOUT" or iface in bus:
        if iface == "ETHERNET":
            return "ETH", "INOUT"
        return iface, "INOUT"

    # Convert device direction to ECU direction.
    if dt == "SENSOR":
        ecu_dir = "INPUT" if role in {"OUTPUT", "INOUT", ""} else "OUTPUT"
    elif dt == "ACTUATOR":
        ecu_dir = "OUTPUT" if role in {"INPUT", "INOUT", ""} else "INPUT"
    else:
        ecu_dir = "INPUT" if role == "OUTPUT" else "OUTPUT" if role == "INPUT" else "INOUT"

    if ecu_dir == "INPUT":
        if iface in {"ANALOG", "VOLTAGE", "ANALOG_VOLTAGE"}:
            return "AI", ecu_dir
        if iface in {"DIGITAL", "SWITCH_HIGHSIDE", "SWITCH_HIGHSIDE_SMALL"}:
            return "DI", ecu_dir
        if iface == "FREQUENCY":
            return "FI", ecu_dir
        if iface == "SENT":
            return "SENT", ecu_dir
        if iface in {"CURRENT", "ANALOG_CURRENT"}:
            return "CURR", ecu_dir
        if iface == "RESISTANCE":
            return "RES", ecu_dir
        if iface == "TEMPERATURE":
            return "TEMP", ecu_dir
        return "OTHER", ecu_dir

    if ecu_dir == "OUTPUT":
        if iface in {"PWM", "PWM_HIGHSIDE", "PWM_LOWSIDE"}:
            if iface == "PWM_HIGHSIDE" or "HIGH_SIDE" in flags_u:
                return "PWM_HS", ecu_dir
            if iface == "PWM_LOWSIDE" or "LOW_SIDE" in flags_u:
                return "PWM_LS", ecu_dir
            return "PWM", ecu_dir
        if iface in {"DIGITAL", "SWITCH_HIGHSIDE", "SWITCH_HIGHSIDE_SMALL", "LED_LOWSIDE"}:
            if iface in {"SWITCH_HIGHSIDE", "SWITCH_HIGHSIDE_SMALL"} or "HIGH_SIDE" in flags_u:
                return "DO_HS", ecu_dir
            if iface == "LED_LOWSIDE" or "LOW_SIDE" in flags_u:
                return "DO_LS", ecu_dir
            return "DO", ecu_dir
        if iface in {"CURRENT", "ANALOG_CURRENT"}:
            return "CURR", ecu_dir
        if iface in {"ANALOG", "VOLTAGE"}:
            return "AI", ecu_dir
        return "OTHER", ecu_dir

    return "INOUT", "INOUT"


@dataclass
class Demand:
    counts: Counter[str] = field(default_factory=Counter)
    rows: list[dict[str, Any]] = field(default_factory=list)

    def add(self, code: str, row: dict[str, Any]) -> None:
        if not code:
            return
        self.counts[code] += 1
        r = dict(row)
        r["io_code"] = code
        self.rows.append(r)

    def merge(self, other: "Demand") -> None:
        self.counts.update(other.counts)
        self.rows.extend(other.rows)

    def as_json(self) -> dict[str, Any]:
        return {"counts": dict(sorted(self.counts.items())), "rows": self.rows, "total_pins": int(sum(self.counts.values()))}


def normalize_device(dev: dict[str, Any], cfg: dict[str, Any], system_name: str, index: int) -> dict[str, Any]:
    dtype = str(dev.get("_viewer_device_type") or norm_device_type(dev)).upper()
    name = best_str(dev, ["name", "id", "part_number", "supplier_pn"], f"Device_{index+1}")
    did = clean_id(dev.get("id") or f"{system_name}_{name}_{index}")

    connectors = [x for x in dev.get("connectors", []) if isinstance(x, dict)] if isinstance(dev.get("connectors"), list) else []
    signals = [x for x in dev.get("signals", []) if isinstance(x, dict)] if isinstance(dev.get("signals"), list) else []
    sig_index = build_signal_index(signals, cfg)
    pins = [x for x in dev.get("pins", []) if isinstance(x, dict)] if isinstance(dev.get("pins"), list) else []

    elec_labels = {str(k): str(v) for k, v in cfg.get("electrical_flags", {}).items()}
    diag_labels = {str(k): str(v) for k, v in cfg.get("diagnostic_flags", {}).items()}
    demand = Demand()
    norm_pins: list[dict[str, Any]] = []

    def add_endpoint(pin: dict[str, Any], sig: dict[str, Any], ordinal: int, inferred: bool = False, signal_name_override: str = "") -> None:
        signal_name = signal_name_override or signal_ref_from_pin(pin, cfg) or signal_id(sig, cfg) or f"Signal_{ordinal}"
        interface = get_interface(pin, cfg.get("pin_interface_keys", [])) or get_interface(sig, cfg.get("signal_interface_keys", []))
        role = get_role(pin) or get_role(sig, cfg.get("signal_role_keys", []))
        pnum = ""
        for key in cfg.get("pin_number_keys", []):
            if key in pin:
                pnum = str(pin.get(key)); break
        elec_value = pin.get("electrical_requirement", sig.get("electrical_requirement", pin.get("electrical_capability", 0)))
        flags = unique(decode_bitmask(elec_value, elec_labels) + infer_flags_from_text(pin.get("name"), pin.get("group"), pin.get("electrical"), sig.get("prefix"), sig.get("interface")))
        diag_value = pin.get("diagnostics_required", pin.get("diagnostic_flags", sig.get("diagnostics_required", sig.get("diagnostic_flags", 0))))
        diags = decode_bitmask(diag_value, diag_labels)
        io_code, ecu_dir = classify_io(dtype, role, interface, flags, cfg)
        row = {
            "id": clean_id(pin.get("id") or f"{did}_pin_{ordinal}"),
            "number": pnum or str(ordinal),
            "name": best_str(pin, ["name"], signal_name if inferred else f"Pin {ordinal}"),
            "connector": best_str(pin, ["connector", "connector_name"], connectors[0].get("name", "") if connectors else ""),
            "cavity": pin.get("cavity", pin.get("physical_number", pnum or ordinal)),
            "role": role,
            "interface": interface,
            "signal": signal_name,
            "io_code": io_code,
            "ecu_direction": ecu_dir,
            "electrical_flags": flags,
            "diagnostic_flags": diags,
            "inferred_from_signal": inferred,
            "source": pin,
            "signal_source": sig,
        }
        norm_pins.append(row)
        demand.add(io_code, {
            "system": system_name, "device": name, "device_type": dtype,
            "pin": row["name"], "pin_number": row["number"], "connector": row["connector"],
            "signal": signal_name, "interface": interface, "role": role,
            "ecu_direction": ecu_dir, "electrical_flags": flags, "inferred_from_signal": inferred,
        })

    if pins:
        for i, pin in enumerate(pins, 1):
            sig_ref = signal_ref_from_pin(pin, cfg)
            sig = sig_index.get(sig_ref) or (pin.get("signal") if isinstance(pin.get("signal"), dict) else {}) or {}
            add_endpoint(pin, sig, i, False)
    else:
        # Legacy compact device: create one logical endpoint per expanded signal.
        ordinal = 1
        for sig in signals:
            names = expanded_signal_names(sig, cfg) or [signal_id(sig, cfg) or f"Signal_{ordinal}"]
            for name_i in names:
                add_endpoint({}, sig, ordinal, True, name_i)
                ordinal += 1

    return {
        "id": did,
        "name": name,
        "type": dtype,
        "component": str(dev.get("_viewer_component_name", "")),
        "component_properties": dev.get("_viewer_component", {}),
        "properties": {k: v for k, v in dev.items() if not k.startswith("_viewer_") and k not in ("connectors", "signals", "pins")},
        "connectors": connectors,
        "signals": signals,
        "pins": norm_pins,
        "io": demand.as_json(),
    }


def normalize_system(data: dict[str, Any], path: Path, cfg: dict[str, Any]) -> dict[str, Any]:
    name = best_str(data, ["name", "id", "part_number"], path.stem)
    raw_devices = collect_devices(data, cfg)
    devices = [normalize_device(d, cfg, name, i) for i, d in enumerate(raw_devices)]
    demand = Demand()
    for d in devices:
        demand.counts.update(d.get("io", {}).get("counts", {}))
        demand.rows.extend(d.get("io", {}).get("rows", []))
    return {
        "id": clean_id(data.get("id") or name),
        "name": name,
        "source_file": str(path),
        "source_file_name": path.name,
        "properties": {k: v for k, v in data.items() if k not in ("components", "devices", "sensors", "actuators")},
        "devices": devices,
        "io": demand.as_json(),
        "stats": {
            "components": len(data.get("components", [])) if isinstance(data.get("components"), list) else 0,
            "devices": len(devices),
            "sensors": sum(1 for d in devices if d["type"] == "SENSOR"),
            "actuators": sum(1 for d in devices if d["type"] == "ACTUATOR"),
            "connectors": sum(len(d.get("connectors", [])) for d in devices),
            "signals": sum(sum(max(1, to_int(s.get("count", 1), 1)) for s in d.get("signals", []) if isinstance(s, dict)) for d in devices),
            "pins": sum(len(d.get("pins", [])) for d in devices),
            "io_total": int(sum(demand.counts.values())),
        },
    }


def load_systems(root: Path, raw_input: str | None, cfg: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    systems: list[dict[str, Any]] = []
    issues: list[dict[str, Any]] = []
    for p in discover_files(root, raw_input, cfg):
        try:
            data = read_json(p)
        except Exception as exc:
            issues.append({"level": "ERROR", "file": str(p), "message": f"JSON read failed: {exc}"})
            continue
        if not looks_like_system(data, cfg):
            issues.append({"level": "INFO", "file": str(p), "message": "Skipped: not a system JSON"})
            continue
        try:
            systems.append(normalize_system(data, p, cfg))
        except Exception as exc:
            issues.append({"level": "ERROR", "file": str(p), "message": f"normalization failed: {exc}"})
    systems.sort(key=lambda s: s["name"].lower())
    # Make display names unique. Some generated workspaces contain both a normalized
    # system and an explicit_originals copy with the same top-level name. The viewer
    # uses system names as UI keys, so duplicate names must be disambiguated while
    # preserving the original JSON name for traceability.
    name_counts = Counter(s["name"] for s in systems)
    if any(v > 1 for v in name_counts.values()):
        for item in systems:
            if name_counts[item["name"]] > 1:
                original = item["name"]
                src = Path(item.get("source_file", item.get("source_file_name", "")))
                parent = src.parent.name if src.parent.name else "source"
                item["original_name"] = original
                item["name"] = f"{original} [{parent}/{item.get('source_file_name', src.name)}]"
                item["id"] = clean_id(item["name"])
    return systems, issues


def load_selection(path: Path | None) -> dict[str, Any]:
    if path and path.exists():
        data = read_json(path)
        if isinstance(data, dict):
            return data
    return {}


def build_selection_model(systems: list[dict[str, Any]], sel: dict[str, Any]) -> dict[str, Any]:
    names = [s["name"] for s in systems]
    name_set = set(names)
    always = [x for x in sel.get("always_active", []) if x in name_set]
    used = set(always)
    groups = []
    for idx, g in enumerate(sel.get("exclusive_groups", [])):
        if not isinstance(g, dict):
            continue
        members = [x for x in g.get("systems", []) if x in name_set]
        if not members:
            continue
        used.update(members)
        groups.append({
            "id": clean_id(g.get("id") or g.get("name") or f"group_{idx+1}"),
            "name": str(g.get("name") or f"Exclusive group {idx+1}"),
            "description": str(g.get("description") or "One system mounted at a time"),
            "systems": members,
            "default": g.get("default") if g.get("default") in members else members[0],
        })
    return {
        "configuration_name": sel.get("configuration_name", "Machine configuration"),
        "always_active": always,
        "exclusive_groups": groups,
        "manual_systems": [n for n in names if n not in used],
    }


def ordered_counts(counts: dict[str, int], cfg: dict[str, Any]) -> list[dict[str, Any]]:
    cat = cfg.get("_category_by_code", {})
    order = cfg.get("_category_order", [])
    keys = [k for k in order if counts.get(k, 0)] + sorted(k for k in counts if k not in order and counts.get(k, 0))
    return [
        {"code": k, "count": int(counts.get(k, 0)), "label": cat.get(k, {}).get("label", k), "description": cat.get(k, {}).get("description", "")}
        for k in keys
    ]


def make_payload(root: Path, systems: list[dict[str, Any]], issues: list[dict[str, Any]], cfg: dict[str, Any], selection_cfg: dict[str, Any]) -> dict[str, Any]:
    aggregate = Counter()
    for s in systems:
        aggregate.update(s.get("io", {}).get("counts", {}))
        s["io"]["ordered"] = ordered_counts(s["io"].get("counts", {}), cfg)
    summary = {
        "systems": len(systems),
        "devices": sum(s["stats"]["devices"] for s in systems),
        "sensors": sum(s["stats"]["sensors"] for s in systems),
        "actuators": sum(s["stats"]["actuators"] for s in systems),
        "pins": sum(s["stats"]["pins"] for s in systems),
        "signals": sum(s["stats"]["signals"] for s in systems),
        "io_aggregate_sum": dict(sorted(aggregate.items())),
    }
    return {
        "schema_version": "eec-system-viewer-data-2.0",
        "title": cfg.get("title", DEFAULT_CONFIG["title"]),
        "generator": SCRIPT_NAME,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "root": str(root),
        "io_categories": cfg.get("io_categories", []),
        "systems": systems,
        "selection": build_selection_model(systems, selection_cfg),
        "issues": issues,
        "summary": summary,
    }


def json_for_html(data: Any) -> str:
    return json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")

# ---------------------------------------------------------------------------
# HTML Renderer
# ---------------------------------------------------------------------------

def render_html(payload: dict[str, Any]) -> str:
    title = esc(payload.get("title", DEFAULT_CONFIG["title"]))
    data = json_for_html(payload)
    return f"""<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title}</title>
<style>
:root {{
  --bg:#070b12; --paper:#0f1622; --paper2:#151e2e; --ink:#cfdaea; --muted:#6c83a2;
  --line:#233149; --accent:#2ee6ff; --accent2:#2ee6a0; --green:#2ee6a0; --orange:#ffb43d;
  --red:#ff5a78; --purple:#b388ff; --shadow:0 8px 30px rgba(0,0,0,.45); --r:18px;
}}
*{{box-sizing:border-box}} body{{margin:0;font-family:'Segoe UI',system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--ink)}}
button,input,select{{font:inherit}} .app{{display:grid;grid-template-columns:340px minmax(0,1fr) 380px;min-height:100vh}} .sidebar{{position:sticky;top:0;height:100vh;overflow:auto;padding:20px;border-right:1px solid var(--line);background:rgba(11,16,24,.92);backdrop-filter:blur(12px)}} .main{{padding:26px;min-width:0}} .inspect{{position:sticky;top:0;height:100vh;overflow:auto;border-left:1px solid var(--line);background:rgba(11,16,24,.95);padding:18px}}
.hero{{background:radial-gradient(circle at top right,rgba(46,230,255,.18),transparent 30%),linear-gradient(135deg,#0b1018,#0a4456 55%,#03211a);color:var(--ink);border-radius:26px;padding:30px;box-shadow:var(--shadow);margin-bottom:18px}} .hero h1{{margin:0;font-size:clamp(28px,3.4vw,48px);letter-spacing:-.045em;line-height:1.05;color:var(--ink)}} .hero p{{margin:10px 0 0;color:var(--muted);max-width:92ch}} .hero .chips{{margin-top:16px;display:flex;gap:8px;flex-wrap:wrap}}
.chip{{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:999px;background:rgba(46,230,255,.1);color:var(--accent);border:1px solid rgba(46,230,255,.25);font-size:11px;font-weight:900;white-space:nowrap}} .hero .chip{{background:rgba(46,230,255,.1);border-color:rgba(46,230,255,.25);color:var(--accent)}}
.card{{background:var(--paper);border:1px solid var(--line);border-radius:var(--r);box-shadow:0 6px 24px rgba(0,0,0,.25);padding:18px;margin-bottom:18px}} .card h2,.card h3{{margin:0 0 12px;letter-spacing:-.02em;color:var(--ink)}} .card h2{{font-size:22px}} .card h3{{font-size:17px}} .sub{{color:var(--muted);font-size:13px}}
.tabs{{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 18px}} .tab{{border:1px solid var(--line);background:var(--paper2);border-radius:999px;padding:10px 14px;font-weight:900;cursor:pointer;color:var(--muted)}} .tab.active{{background:var(--accent);border-color:var(--accent);color:#000}} .view{{display:none}} .view.active{{display:block}}
.search{{width:100%;padding:12px 14px;border:1px solid var(--line);border-radius:14px;margin:12px 0;background:var(--paper2);color:var(--ink)}} .side-title{{margin:0;font-size:22px;letter-spacing:-.02em;color:var(--ink)}} .system-row{{width:100%;text-align:left;background:var(--paper2);border:1px solid var(--line);padding:12px;border-radius:14px;margin-bottom:8px;cursor:pointer;color:var(--ink)}} .system-row.active,.system-row:hover{{border-color:var(--accent);box-shadow:0 0 0 4px rgba(46,230,255,.1)}} .system-row .name{{font-weight:950}} .system-row .meta{{font-size:12px;color:var(--muted);margin-top:4px}}
.kpis{{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:12px}} .kpi{{border:1px solid var(--line);border-radius:16px;padding:14px;background:var(--paper2)}} .kpi .k{{font-size:11px;color:var(--muted);font-weight:900;letter-spacing:.06em;text-transform:uppercase}} .kpi .v{{font-size:29px;font-weight:950;margin-top:5px;color:var(--accent)}}
.io-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px}} .io-card{{border:1px solid var(--line);border-radius:16px;padding:14px;background:var(--paper2);position:relative;overflow:hidden;cursor:pointer}} .io-card:before{{content:"";position:absolute;left:0;top:0;bottom:0;width:5px;background:var(--accent)}} .io-code{{font-weight:950;font-size:21px;color:var(--accent)}} .io-label{{font-size:11px;color:var(--muted);font-weight:850;text-transform:uppercase;line-height:1.2}} .io-count{{font-size:36px;font-weight:950;margin-top:6px}}
.bar-list{{display:grid;gap:9px}} .bar-row{{display:grid;grid-template-columns:78px 1fr 46px;gap:10px;align-items:center}} .bar-name{{font-weight:950}} .bar-bg{{height:12px;background:var(--line);border-radius:999px;overflow:hidden}} .bar{{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--accent),var(--accent2));min-width:2px}}
.graph{{display:grid;grid-template-columns:minmax(180px,1fr) 260px minmax(180px,1fr);gap:16px;align-items:center;min-width:0}} .lane-title{{font-size:12px;color:var(--muted);font-weight:950;text-transform:uppercase;letter-spacing:.07em;margin-bottom:8px}} .node-list{{display:grid;gap:10px;min-width:0}} .node{{border:1px solid var(--line);background:var(--paper2);border-radius:16px;padding:12px;cursor:pointer;transition:.15s;color:var(--ink);min-width:0;overflow-wrap:anywhere;word-break:break-word}} .node:hover,.node.focus{{transform:translateY(-1px);border-color:var(--accent);box-shadow:0 0 0 4px rgba(46,230,255,.09)}} .node.sensor{{border-left:6px solid var(--green)}} .node.actuator{{border-left:6px solid var(--orange)}} .node.center{{text-align:center;border-left:0;background:linear-gradient(135deg,#0a4456,var(--paper2))}} .node .title{{font-weight:950;overflow-wrap:anywhere;word-break:break-word}} .node .small{{color:var(--muted);font-size:12px;margin-top:4px;overflow-wrap:anywhere;word-break:break-word}} .arrow{{text-align:center;color:var(--muted);font-weight:950}}
.selection-panel{{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}} .checkbox-list{{display:grid;gap:8px;max-height:360px;overflow:auto;padding-right:4px}} label.check{{display:flex;gap:9px;align-items:flex-start;border:1px solid var(--line);border-radius:14px;padding:10px;background:var(--paper2);cursor:pointer;color:var(--ink)}} label.check:hover{{border-color:var(--accent)}} label.check input{{width:18px;height:18px;margin-top:1px}} .mode-toggle{{display:flex;gap:8px;flex-wrap:wrap}} .mode-toggle button{{border:1px solid var(--line);background:var(--paper2);border-radius:999px;padding:9px 12px;font-weight:900;cursor:pointer;color:var(--muted)}} .mode-toggle button.active{{background:var(--accent2);border-color:var(--accent2);color:#000}}
.table-wrap{{overflow:auto;border:1px solid var(--line);border-radius:14px}} table{{width:100%;border-collapse:collapse;font-size:13px}} th,td{{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top;color:var(--ink)}} th{{position:sticky;top:0;background:var(--paper2);z-index:1;text-align:left;font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.045em}} tr:hover td{{background:var(--paper2)}}
.badge{{display:inline-flex;margin:2px;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:950;background:rgba(46,230,255,.1);color:var(--accent)}} .badge.sensor{{background:rgba(46,230,160,.1);color:var(--green)}} .badge.actuator{{background:rgba(255,180,61,.1);color:var(--orange)}} .badge.warn{{background:rgba(255,90,120,.1);color:var(--red)}} .badge.ok{{background:rgba(46,230,160,.1);color:var(--green)}}
.detail-title{{font-size:20px;font-weight:950;margin-bottom:4px;color:var(--ink)}} .detail-sub{{color:var(--muted);font-size:13px;margin-bottom:12px}} .facts{{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px}} .fact{{border:1px solid var(--line);background:var(--paper2);border-radius:12px;padding:9px}} .fact .fk{{font-size:10px;color:var(--muted);font-weight:950;text-transform:uppercase;letter-spacing:.06em}} .fact .fv{{font-weight:900;word-break:break-word;margin-top:3px;color:var(--ink)}} pre{{white-space:pre-wrap;overflow:auto;background:#0b1018;color:#cfdaea;border-radius:14px;padding:14px;font-size:12px;line-height:1.45;max-height:58vh}}
.matrix th:first-child,.matrix td:first-child{{position:sticky;left:0;background:var(--paper2);z-index:2}} .matrix th:first-child{{background:var(--paper2);z-index:3}}
@media(max-width:1220px){{.app{{grid-template-columns:1fr}}.sidebar,.inspect{{position:relative;height:auto}}.selection-panel,.graph{{grid-template-columns:1fr}}.arrow{{display:none}}}}
</style>
</head>
<body>
<div class="app">
  <aside class="sidebar"><h2 class="side-title">System selector</h2><p class="sub">Choisir un système ou cocher plusieurs systèmes alternatifs.</p><input class="search" id="search" placeholder="Search system, device, signal…"/><div id="systemList"></div></aside>
  <main class="main">
    <section class="hero"><h1>{title}</h1><p>Visualisation graphique des systèmes JSON et calcul du nombre d'entrées-sorties ECU à réserver par type: AI, DIGITAL, PWM, SENT, CURR, RES, CAN, supply, ground, etc.</p><div class="chips" id="heroChips"></div></section>
    <div class="tabs"><button class="tab active" data-view="single">Système sélectionné</button><button class="tab" data-view="multi">Sélection multi-systèmes</button><button class="tab" data-view="matrix">Matrice I/O</button><button class="tab" data-view="details">Détails JSON</button></div>
    <section class="view active" id="single"></section><section class="view" id="multi"></section><section class="view" id="matrix"></section><section class="view" id="details"></section>
  </main>
  <aside class="inspect"><div class="detail-title" id="dt">Object details</div><div class="detail-sub" id="ds">Survole ou clique un système, capteur, actionneur, pin ou signal.</div><div class="facts" id="facts"></div><pre id="jsonView">{{}}</pre></aside>
</div>
<script id="payload" type="application/json">{data}</script>
<script>
const DATA=JSON.parse(document.getElementById('payload').textContent);const SYSTEMS=DATA.systems||[];const CATS=DATA.io_categories||[];const CATMAP=Object.fromEntries(CATS.map(c=>[c.code,c]));let selected=SYSTEMS[0]?.name||'';let mode='alternative';let pinned=null;
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));function esc(s){{return String(s??'').replace(/[&<>\"]/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}}[c]));}}function sys(n){{return SYSTEMS.find(s=>s.name===n)}}function sidx(n){{return Math.max(0,SYSTEMS.findIndex(s=>s.name===n))}}function total(c){{return Object.values(c||{{}}).reduce((a,b)=>a+Number(b||0),0)}}function ordered(c){{const keys=CATS.map(x=>x.code).filter(k=>c&&c[k]);return keys.concat(Object.keys(c||{{}}).filter(k=>!keys.includes(k)&&c[k]).sort()).map(k=>[k,Number(c[k]||0)]);}}function chip(t,cl=''){{return `<span class="badge ${{cl}}">${{esc(t)}}</span>`}}
function kpis(items){{return `<div class="kpis">${{items.map(x=>`<div class="kpi"><div class="k">${{esc(x.k)}}</div><div class="v">${{esc(x.v)}}</div></div>`).join('')}}</div>`}}
function ioCards(counts){{const entries=ordered(counts);if(!entries.length)return '<p class="sub">No I/O demand detected.</p>';return `<div class="io-grid">${{entries.map(([k,v])=>`<div class="io-card" data-inspect='${{JSON.stringify({{kind:'I/O bucket',code:k,label:CATMAP[k]?.label||k,count:v,description:CATMAP[k]?.description||''}})}}'><div class="io-code">${{esc(k)}}</div><div class="io-label">${{esc(CATMAP[k]?.label||k)}}</div><div class="io-count">${{v}}</div></div>`).join('')}}</div>`}}
function bars(counts){{const entries=ordered(counts);const max=Math.max(1,...entries.map(x=>x[1]));return `<div class="bar-list">${{entries.map(([k,v])=>`<div class="bar-row"><div class="bar-name">${{esc(k)}}</div><div class="bar-bg"><div class="bar" style="width:${{Math.max(3,v/max*100)}}%"></div></div><div><strong>${{v}}</strong></div></div>`).join('')}}</div>`}}
function setInspect(title,sub,obj,facts={{}}){{if(pinned&&!obj.__force)return;$('#dt').textContent=title;$('#ds').textContent=sub||'';$('#facts').innerHTML=Object.entries(facts).filter(([k,v])=>v!==undefined&&v!==null&&String(v)!=='').map(([k,v])=>`<div class="fact"><div class="fk">${{esc(k)}}</div><div class="fv">${{esc(v)}}</div></div>`).join('');$('#jsonView').textContent=JSON.stringify(obj,null,2)}}function inspectPayload(payload){{if(!payload)return;setInspect(payload.kind||'Object',payload.label||'',payload,payload)}}function bind(root=document){{root.querySelectorAll('[data-inspect]').forEach(el=>{{el.onmouseenter=()=>{{try{{inspectPayload(JSON.parse(el.dataset.inspect))}}catch(e){{}}}};el.onclick=()=>{{try{{const o=JSON.parse(el.dataset.inspect);o.__force=true;pinned=o;inspectPayload(o)}}catch(e){{}}}}}})}}
function renderSystemList(){{const q=$('#search').value.toLowerCase();$('#systemList').innerHTML=SYSTEMS.filter(s=>!q||JSON.stringify(s).toLowerCase().includes(q)).map(s=>`<button class="system-row ${{s.name===selected?'active':''}}" data-system="${{esc(s.name)}}"><div class="name">${{esc(s.name)}}</div><div class="meta">${{s.stats.devices}} devices · ${{s.stats.pins}} pins · ${{s.stats.io_total}} ECU I/O</div></button>`).join('');$$('.system-row').forEach(b=>b.onclick=()=>{{selected=b.dataset.system;renderAll();}})}}
function systemGraph(s,si){{const sensors=s.devices.filter(d=>d.type==='SENSOR'),acts=s.devices.filter(d=>d.type==='ACTUATOR');const node=(d,di)=>`<div class="node ${{d.type==='SENSOR'?'sensor':'actuator'}}" data-inspect='${{JSON.stringify({{kind:d.type,label:d.name,component:d.component,pins:d.pins.length,io:d.io.counts,properties:d.properties}})}}'><div class="title">${{esc(d.name)}}</div><div class="small">${{chip(d.type,d.type==='SENSOR'?'sensor':'actuator')}} ${{d.pins.length}} pins · ${{total(d.io.counts)}} I/O</div></div>`;return `<div class="graph"><div><div class="lane-title">Sensors</div><div class="node-list">${{sensors.map(node).join('')||'<p class="sub">No sensors</p>'}}</div></div><div><div class="node center" data-inspect='${{JSON.stringify({{kind:'System',label:s.name,source:s.source_file_name,stats:s.stats,properties:s.properties,io:s.io.counts}})}}'><div class="title">${{esc(s.name)}}</div><div class="small">${{s.stats.devices}} devices<br/>${{s.stats.io_total}} ECU I/O pins</div></div><div class="arrow">Sensors → System → Actuators</div></div><div><div class="lane-title">Actuators</div><div class="node-list">${{acts.map(node).join('')||'<p class="sub">No actuators</p>'}}</div></div></div>`}}
function singleView(){{const s=sys(selected)||SYSTEMS[0];if(!s){{$('#single').innerHTML='<div class="card">No systems loaded.</div>';return}}const si=sidx(s.name);$('#single').innerHTML=`<div class="card"><h2>${{esc(s.name)}}</h2><p class="sub">Besoin ECU I/O exact pour le système sélectionné. Exemple: AI=entrées analogiques, DI=entrées digitales, FI=fréquence, CURR=courant, RES=résistance, PWM/DO=sorties ECU.</p>${{kpis([{{k:'Devices',v:s.stats.devices}},{{k:'Sensors',v:s.stats.sensors}},{{k:'Actuators',v:s.stats.actuators}},{{k:'ECU I/O pins',v:s.stats.io_total}}])}}</div><div class="card"><h2>I/O ECU à réserver pour ce système</h2>${{ioCards(s.io.counts)}}</div><div class="card"><h2>Représentation graphique du système</h2>${{systemGraph(s,si)}}</div><div class="card"><h2>Détail des pins et signaux</h2>${{pinTable(s)}}</div>`;bind($('#single'));}}
function pinTable(s){{const rows=[];s.devices.forEach((d,di)=>d.pins.forEach((p,pi)=>rows.push({{d,di,p,pi}})));return `<div class="table-wrap"><table><thead><tr><th>Device</th><th>Type</th><th>Connector</th><th>Pin</th><th>Signal</th><th>Interface</th><th>Role</th><th>ECU direction</th><th>I/O</th></tr></thead><tbody>${{rows.map(r=>`<tr data-inspect='${{JSON.stringify({{kind:'Pin',device:r.d.name,type:r.d.type,connector:r.p.connector,pin:r.p.number,signal:r.p.signal,interface:r.p.interface,role:r.p.role,io_code:r.p.io_code,ecu_direction:r.p.ecu_direction,electrical_flags:r.p.electrical_flags,diagnostic_flags:r.p.diagnostic_flags,source:r.p.source,signal_source:r.p.signal_source}})}}'><td><strong>${{esc(r.d.name)}}</strong></td><td>${{chip(r.d.type,r.d.type==='SENSOR'?'sensor':'actuator')}}</td><td>${{esc(r.p.connector)}}</td><td>${{esc(r.p.number)}}</td><td>${{esc(r.p.signal)}}</td><td>${{esc(r.p.interface)}}</td><td>${{esc(r.p.role)}}</td><td>${{esc(r.p.ecu_direction)}}</td><td>${{chip(r.p.io_code)}}</td></tr>`).join('')}}</tbody></table></div>`}}
function selectedNames(){{return $$('.multi-check:checked').map(x=>x.value)}}function sumCounts(names){{const out={{}};names.forEach(n=>{{const s=sys(n);if(!s)return;Object.entries(s.io.counts||{{}}).forEach(([k,v])=>out[k]=(out[k]||0)+Number(v||0));}});return out}}function maxCounts(names){{const out={{}},drivers={{}};names.forEach(n=>{{const s=sys(n);if(!s)return;Object.entries(s.io.counts||{{}}).forEach(([k,v])=>{{v=Number(v||0);if(v>(out[k]||0)){{out[k]=v;drivers[k]=n}}}})}});return {{counts:out,drivers}}}}
function multiView(){{const names=selectedNames();const alt=maxCounts(names),sum=sumCounts(names),active=mode==='alternative'?alt.counts:sum;$('#multi').innerHTML=`<div class="selection-panel"><div class="card"><h2>Sélection multi-systèmes</h2><p class="sub"><strong>Mode alternatives:</strong> plusieurs systèmes sont sélectionnés, mais un seul est monté à la fois. Le nombre de pins à réserver est donc le maximum par type I/O, pas la somme.</p><div class="mode-toggle"><button class="${{mode==='alternative'?'active':''}}" data-mode="alternative">Alternatives: max par type</button><button class="${{mode==='cumulative'?'active':''}}" data-mode="cumulative">Cumulatif: somme</button></div><div style="margin:12px 0;display:flex;gap:8px;flex-wrap:wrap"><button onclick="checkAll(true)">Select all</button><button onclick="checkAll(false)">Clear</button></div><div class="checkbox-list">${{SYSTEMS.map(s=>`<label class="check"><input class="multi-check" type="checkbox" value="${{esc(s.name)}}" ${{names.includes(s.name)?'checked':''}}><span><strong>${{esc(s.name)}}</strong><br><span class="sub">${{s.stats.io_total}} I/O pins · ${{s.stats.devices}} devices</span></span></label>`).join('')}}</div></div><div class="card"><h2>Résultat: pins ECU à réserver</h2><p>${{names.length?names.map(n=>chip(n)).join(' '):'<span class="sub">Aucun système sélectionné.</span>'}}</p>${{ioCards(active)}}<h3 style="margin-top:18px">Graphique</h3>${{bars(active)}}</div></div><div class="card"><h2>Alternative sizing details</h2>${{alternativeTable(names,alt)}}</div>`;$$('.multi-check').forEach(x=>x.onchange=multiView);$$('[data-mode]').forEach(b=>b.onclick=()=>{{mode=b.dataset.mode;multiView();}});bind($('#multi'));}}
function checkAll(v){{$$('.multi-check').forEach(x=>x.checked=v);multiView()}}window.checkAll=checkAll;
function alternativeTable(names,alt){{if(!names.length)return '<p class="sub">Select systems to compute reservation sizing.</p>';const keys=ordered(mode==='alternative'?alt.counts:sumCounts(names)).map(x=>x[0]);return `<div class="table-wrap"><table><thead><tr><th>I/O type</th><th>Reserved pins</th><th>Driver / reason</th><th>Per selected system</th></tr></thead><tbody>${{keys.map(k=>`<tr><td><strong>${{esc(k)}}</strong><div class="sub">${{esc(CATMAP[k]?.label||'')}}</div></td><td><strong>${{mode==='alternative'?(alt.counts[k]||0):(sumCounts(names)[k]||0)}}</strong></td><td>${{mode==='alternative'?esc(alt.drivers[k]||''):'Sum of selected systems'}}</td><td>${{names.map(n=>{{const s=sys(n);return chip(`${{n}}: ${{s?.io?.counts?.[k]||0}}`)}}).join('')}}</td></tr>`).join('')}}</tbody></table></div>`}}
function matrixView(){{const codes=CATS.map(c=>c.code).filter(k=>SYSTEMS.some(s=>s.io.counts&&s.io.counts[k]));$('#matrix').innerHTML=`<div class="card"><h2>Matrice I/O par système</h2><p class="sub">Comparer les besoins de chaque système. Pour des systèmes alternatifs, réserver le maximum par colonne.</p><div class="table-wrap"><table class="matrix"><thead><tr><th>System</th><th>Total</th>${{codes.map(k=>`<th>${{esc(k)}}<div class="sub">${{esc(CATMAP[k]?.label||'')}}</div></th>`).join('')}}</tr></thead><tbody>${{SYSTEMS.map(s=>`<tr data-inspect='${{JSON.stringify({{kind:'System',label:s.name,io:s.io.counts,stats:s.stats,source:s.source_file_name}})}}'><td><strong>${{esc(s.name)}}</strong><div class="sub">${{esc(s.source_file_name)}}</div></td><td><strong>${{s.stats.io_total}}</strong></td>${{codes.map(k=>`<td>${{s.io.counts[k]||0}}</td>`).join('')}}</tr>`).join('')}}</tbody></table></div></div>`;bind($('#matrix'));}}
function detailsView(){{const s=sys(selected)||SYSTEMS[0];$('#details').innerHTML=`<div class="card"><h2>Détails complets du système sélectionné</h2><div class="two"></div><pre>${{esc(JSON.stringify(s,null,2))}}</pre></div>`}}
function renderHero(){{$('#heroChips').innerHTML=`<span class="chip">${{SYSTEMS.length}} systems</span><span class="chip">${{DATA.summary.devices}} devices</span><span class="chip">${{DATA.summary.pins}} endpoints</span><span class="chip">Generated ${{esc(DATA.generated_at)}}</span>`}}
function renderAll(){{renderHero();renderSystemList();singleView();multiView();matrixView();detailsView();setInspect('System',selected,sys(selected)||{{}},{{system:selected}})}}function show(v){{$$('.view').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#'+v).classList.add('active');bind($('#'+v));}}
$$('.tab').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#search').oninput=renderSystemList;renderAll();
</script>
</body></html>"""

# ---------------------------------------------------------------------------
# Reports / I/O files
# ---------------------------------------------------------------------------

def write_reports(outdir: Path, payload: dict[str, Any], cfg: dict[str, Any]) -> None:
    summary = {
        "generated_at": payload["generated_at"],
        "summary": payload["summary"],
        "systems": [
            {"name": s["name"], "source_file": s["source_file"], "stats": s["stats"], "io_counts": s["io"].get("counts", {})}
            for s in payload.get("systems", [])
        ],
        "issues": payload.get("issues", []),
    }
    write_text(outdir / "system_viewer_summary.json", json.dumps(summary, indent=2, ensure_ascii=False))
    codes = [c["code"] for c in cfg.get("io_categories", []) if isinstance(c, dict) and c.get("code")]
    csv_path = outdir / "system_io_matrix.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["system", "source_file", "total_pins", *codes])
        for s in payload.get("systems", []):
            counts = s.get("io", {}).get("counts", {})
            writer.writerow([s["name"], s["source_file_name"], s["stats"]["io_total"], *[counts.get(code, 0) for code in codes]])


def generate(root: Path, input_path: str | None, outdir: Path, config_path: Path | None, selection_path: Path | None, verbose: bool = False) -> Path:
    cfg = load_config(config_path)
    systems, issues = load_systems(root, input_path, cfg)
    selection = load_selection(selection_path)
    payload = make_payload(root, systems, issues, cfg, selection)
    html = render_html(payload)
    out_html = outdir / str(cfg.get("output_html", "index.html"))
    write_text(out_html, html)
    write_reports(outdir, payload, cfg)
    if verbose:
        print(f"[OK] Systems loaded: {len(systems)}")
        print(f"[OK] Output HTML: {out_html}")
        print(f"[OK] Summary: {outdir / 'system_viewer_summary.json'}")
        print(f"[OK] Matrix CSV: {outdir / 'system_io_matrix.csv'}")
        if issues:
            print(f"[INFO] Issues/warnings: {len(issues)}")
    return out_html


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate an interactive HTML viewer and ECU I/O sizing report from E/E Architect Design v4 system JSON files.")
    parser.add_argument("--root", default=".", help="Project root / workspace. Default: current directory.")
    parser.add_argument("--input", help="System JSON file, folder, or glob. Default: configured input candidates.")
    parser.add_argument("--out", help="Output folder. Default: config output_dir.")
    parser.add_argument("--config", help="Optional viewer config JSON.")
    parser.add_argument("--selection", help="Optional configuration/exclusive-group JSON.")
    parser.add_argument("--verbose", action="store_true", help="Print progress details.")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    if not root.exists():
        raise SystemExit(f"root not found: {root}")
    config_path = Path(args.config).resolve() if args.config else None
    if config_path is None:
        for cand in (root / "tools" / CONFIG_FILE, Path(__file__).resolve().parent / CONFIG_FILE):
            if cand.exists():
                config_path = cand
                break
    cfg = load_config(config_path)
    outdir = Path(args.out) if args.out else Path(str(cfg.get("output_dir", "generated_doc/system_viewer")))
    if not outdir.is_absolute():
        outdir = root / outdir
    selection_path = Path(args.selection).resolve() if args.selection else None
    if selection_path and not selection_path.exists():
        raise SystemExit(f"selection config not found: {selection_path}")
    html = generate(root, args.input, outdir, config_path, selection_path, args.verbose)
    print(f"Generated: {html}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
