
#!/usr/bin/env python3
from __future__ import annotations
import argparse, html, json, os, re
from pathlib import Path
try:
    import requests
except Exception:
    requests=None

def load_config(path):
    if path and Path(path).exists(): return json.loads(Path(path).read_text(encoding='utf-8'))
    env=os.getenv('POLARION_CONFIG')
    return json.loads(Path(env).read_text(encoding='utf-8')) if env and Path(env).exists() else {}

def text_to_html(text, title):
    parts=[f'<h1>{html.escape(title)}</h1>','<p><em>Generated by E/E Architect Design Polarion script.</em></p>']; in_ul=False
    for line in text.splitlines():
        s=line.strip()
        if not s:
            if in_ul: parts.append('</ul>'); in_ul=False
            continue
        if s.startswith('#'):
            if in_ul: parts.append('</ul>'); in_ul=False
            lvl=min(6,len(s)-len(s.lstrip('#'))+1); parts.append(f'<h{lvl}>{html.escape(s.lstrip("# "))}</h{lvl}>')
        elif s.startswith(('-', '*', '•')):
            if not in_ul: parts.append('<ul>'); in_ul=True
            parts.append(f'<li>{html.escape(s[1:].strip())}</li>')
        else:
            if in_ul: parts.append('</ul>'); in_ul=False
            parts.append(f'<p>{html.escape(s)}</p>')
    if in_ul: parts.append('</ul>')
    return '\n'.join(parts)

def main():
    ap=argparse.ArgumentParser(description='Convert a text/markdown document to Polarion-ready HTML; optional upload hook')
    ap.add_argument('--file', required=True); ap.add_argument('--config'); ap.add_argument('--document'); ap.add_argument('--title'); ap.add_argument('--dry-run', action='store_true'); ap.add_argument('--out')
    args=ap.parse_args(); cfg=load_config(args.config); src=Path(args.file); title=args.title or args.document or src.stem
    out=Path(args.out or cfg.get('export_dir','generated_doc/exports') + '/' + title + '.html'); out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text_to_html(src.read_text(encoding='utf-8'), title), encoding='utf-8')
    if args.dry_run or requests is None: print('[OK] wrote', out); return 0
    if not (os.getenv('POLARION_PAT') or Path('.polarion_pat').exists()): print('[ERROR] missing POLARION_PAT; wrote', out); return 1
    print('[INFO] HTML generated. Add project-specific upload code/config to enable push.'); return 0
if __name__ == '__main__': raise SystemExit(main())
