
#!/usr/bin/env python3
from __future__ import annotations
import argparse, html, json, os, re, sys
from pathlib import Path
try:
    import requests
except Exception:
    requests = None

def load_config(path: Path | None) -> dict:
    if path and path.exists(): return json.loads(path.read_text(encoding='utf-8'))
    env=os.getenv('POLARION_CONFIG')
    if env and Path(env).exists(): return json.loads(Path(env).read_text(encoding='utf-8'))
    return {}

def token(root: Path) -> str | None:
    return os.getenv('POLARION_PAT') or ((root/'.polarion_pat').read_text(encoding='utf-8').strip() if (root/'.polarion_pat').exists() else None)

def parse_requirements(path: Path) -> list[dict]:
    sections=[]; current=None; req=None
    for raw in path.read_text(encoding='utf-8').splitlines():
        line=raw.strip()
        if not line or set(line) <= {'='}: continue
        m=re.match(r'^(REQ[-_A-Za-z0-9.]+)\s*:\s*(.+)$', line)
        if m:
            if current is None: current={'title':'Requirements','requirements':[]}; sections.append(current)
            if req: current['requirements'].append(req)
            req={'id':m.group(1),'text':m.group(2),'example':'','why':''}; continue
        if req and line.lower().startswith('example:'): req['example']=line.split(':',1)[1].strip(); continue
        if req and line.lower().startswith('why:'): req['why']=line.split(':',1)[1].strip(); continue
        if line.isupper() and len(line)>3:
            if req and current: current['requirements'].append(req); req=None
            current={'title':line,'requirements':[]}; sections.append(current)
    if req and current: current['requirements'].append(req)
    return sections

def build_html(sections, title):
    parts=[f'<h1>{html.escape(title)}</h1>','<p><em>Generated by E/E Architect Design Polarion script.</em></p>']
    for sec in sections:
        parts.append(f'<h2>{html.escape(sec["title"])}</h2>')
        for r in sec.get('requirements',[]):
            parts.append(f'<h3>{html.escape(r["id"])}</h3><p>{html.escape(r["text"])}</p>')
            if r.get('example'): parts.append(f'<p><strong>Example:</strong> {html.escape(r["example"])}</p>')
            if r.get('why'): parts.append(f'<p><strong>Why:</strong> {html.escape(r["why"])}</p>')
    return '\n'.join(parts)

def main():
    ap=argparse.ArgumentParser(description='Push structured requirements to Polarion or generate HTML in dry-run mode')
    ap.add_argument('--file', required=True); ap.add_argument('--config', default=None); ap.add_argument('--project'); ap.add_argument('--space'); ap.add_argument('--document'); ap.add_argument('--title', default=None); ap.add_argument('--dry-run', action='store_true'); ap.add_argument('--out', default=None)
    args=ap.parse_args(); root=Path.cwd(); cfg=load_config(Path(args.config) if args.config else None); src=Path(args.file)
    title=args.title or args.document or cfg.get('wiki_design_rules_page') or src.stem
    html_txt=build_html(parse_requirements(src), title)
    out=Path(args.out or cfg.get('export_dir','generated_doc/exports') + '/' + title + '.html')
    out.parent.mkdir(parents=True, exist_ok=True); out.write_text(html_txt, encoding='utf-8')
    if args.dry_run:
        print('[DRY-RUN] wrote', out); return 0
    if requests is None:
        print('[SKIP] requests module unavailable; wrote', out); return 0
    pat=token(root)
    if not pat:
        print('[ERROR] POLARION_PAT or .polarion_pat required unless --dry-run'); return 1
    # Generic endpoint placeholders: project/space/document come from CLI/config.
    server=cfg.get('server_url') or os.getenv('POLARION_URL')
    if not server:
        print('[ERROR] server_url missing in config or POLARION_URL'); return 1
    print('[INFO] HTML generated. Polarion upload endpoint is project-specific; configure your REST call wrapper if needed.'); return 0
if __name__ == '__main__': raise SystemExit(main())
