/**
 * @file    EEC_architecture.h
 * @brief   E/E Architect Design — Public model types and creation APIs.
 * @author  Anadack Temtching Dassi
 * @date    2026
 */
#ifndef EEC_ARCHITECTURE_H
#define EEC_ARCHITECTURE_H

#include "EEC_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/** @brief Agricultural Performance Level (AgPL) assigned to functions or pins.
 *  Ordered low->high so numeric compare works (higher = more capable).
 */
typedef enum EEC_AgplLevel_e {
    EEC_AGPL_A = 0,
    EEC_AGPL_B = 1,
    EEC_AGPL_C = 2,
    EEC_AGPL_D = 3,
    EEC_AGPL_E = 4
} EEC_AgplLevel_t;

struct EEC_Architecture_s;
struct EEC_System_s;
struct EEC_Component_s;
struct EEC_Sensor_s;
struct EEC_Actuator_s;
struct EEC_Signal_s;
struct EEC_Ecu_s;
struct EEC_EcuPin_s;
struct EEC_Connector_s;
struct EEC_Bus_s;
struct EEC_BusNode_s;
struct EEC_Swc_s;
struct EEC_Message_s;

/* Forward typedefs so System/ECU/Bus can reference SWC and CAN-message
 * objects by pointer before their full definitions appear below. */
typedef struct EEC_Swc_s           EEC_Swc_t;
typedef struct EEC_Message_s       EEC_Message_t;
typedef struct EEC_MessageSignal_s EEC_MessageSignal_t;
typedef struct EEC_MessageTx_s     EEC_MessageTx_t;

/** @brief Per-layer ID counters owned by the architecture. */
typedef struct EEC_IdContext_s {
    uint32_t next_architecture_id; /**< Next architecture id. */
    uint32_t next_signal_id;       /**< Next signal id. */
    uint32_t next_system_id;       /**< Next system id. */
    uint32_t next_component_id;    /**< Next component id. */
    uint32_t next_device_id;       /**< Next device id. */
    uint32_t next_device_pin_id;   /**< Next device pin id. */
    uint32_t next_ecu_id;          /**< Next ECU id. */
    uint32_t next_ecu_pin_id;      /**< Next ECU pin id. */
    uint32_t next_bus_id;           /**< Next bus id. */
    uint32_t next_connector_id;     /**< Next connector id. */
    uint32_t next_swc_id;           /**< Next SWC id. */
    uint32_t next_message_id;       /**< Next CAN message id. */
} EEC_IdContext_t;

/** @brief One architecture-level signal.
 *  A signal is the logical information entity later connected to one ECU pin.
 */
typedef struct EEC_Signal_s {
    uint32_t id;                                /**< Unique signal id inside the architecture. */
    bool obsolete;                              /**< True if this object is obsolete (raises warning on use). */
    char name[64];                              /**< Signal name used in exports. */
    char part_number[64];                       /**< Manufacturer or reference part number. */
    EEC_ObjectPriority_t priority;               /**< Relative urgency assigned to the signal. */
    EEC_SafetyClass_t safety;                    /**< Safety classification of the signal. */
    EEC_SignalType_t type;                       /**< Signal payload type. */
    EEC_SignalInterface_t interface_type;        /**< Electrical interface used for routing. */
    EEC_SignalUnit_t unit;                       /**< Signal engineering unit. */
    float min_value;                            /**< Minimum engineering value. */
    float max_value;                            /**< Maximum engineering value. */
    float resolution;                           /**< Resolution or LSB. */
    float scaling;                              /**< Scaling factor. */
    bool is_mapped;                             /**< True once routed to an ECU pin. */
    struct EEC_Architecture_s *owner_architecture; /**< Back-reference to the owner architecture. */
    struct EEC_Swc_s *producer_swc;              /**< SWC computing this signal as a software variable (NULL = device/physical origin). */
    EEC_DigitalStructure_t digital_structure;    /**< Digital input structure (pull-up/pull-down/floating). */
    /* ── Signal Naming Convention (SYSTEM_Function_[POSITION_]TYPE) ── */
    char system_code[8];                        /**< System code (HYDD, BRK, RHIT, BREX, COIL, ELB). */
    char function_name[32];                     /**< Function name in CamelCase (AnglPosn, PressMonit, etc.). */
    char position_index[8];                     /**< Position index (01, 02, etc.) or empty string. */
    char type_code[8];                          /**< Type code (SNSR, SWT, PWR, GND, CAN, LIN, CMD, AI). */
    char clean_signal_name[64];                 /**< Full generated name following SYSTEM_Function_[POSITION_]TYPE. */
    bool is_auto_named;                         /**< True if name was auto-generated by EEC_GenerateCleanSignalName(). */
} EEC_Signal_t;

/** @brief One logical pin on a system device. */
typedef struct EEC_DevicePin_s {
    uint32_t id;                 /**< Unique device pin id. */
    bool obsolete;               /**< True if this object is obsolete (raises warning on use). */
    uint32_t number;             /**< Device-local pin number. */
    EEC_PinRole_t role;           /**< Pin role. */
    uint32_t electrical_requirement; /**< Bitmask of EEC_ElectricalFlag_t the device needs from the ECU pin. */
    EEC_PinInterface_t interface_type; /**< Preferred electrical/communication interface for this device pin. */
    EEC_Signal_t *signal;         /**< Connected logical signal. */
    char name[64];               /**< Optional device-side pin name. */
    /* ── Pre-wiring validation fields ── */
    float nominal_current;       /**< Steady-state current draw (A). 0 = not specified. */
    float inrush_current;        /**< Peak inrush at startup (A). 0 = not specified. */
    float max_voltage;           /**< Absolute max voltage the device produces or tolerates (V). 0 = not specified. */
    uint32_t diagnostics_required; /**< Bitmask of EEC_DiagFlags_t the device NEEDS from the ECU pin. */
    bool safety_relevant;        /**< True if fault detection and safe-state are required. */
    EEC_GroundClass_t ground_class; /**< Required ground type (POWER or LOGIC). */
    EEC_ResetState_t required_reset_state; /**< Expected ECU output state at power-on/reset. */
    /* Preferred/required power supplies for this device pin (optional). */
    EEC_SensorSupplyType_t required_sensor_supply; /**< Preferred sensor supply type (datasheet name or generic). */
    EEC_SensorGroundType_t required_sensor_ground; /**< Preferred sensor ground/return type. */
    float required_supply_voltage; /**< Nominal required supply voltage (V). 0 = unspecified. */
} EEC_DevicePin_t;

/** @brief Physical connector housing on a sensor, actuator, or ECU.
 *  Groups pin cavities under a named reference and captures the
 *  mechanical and electrical characteristics of the housing.
 */
typedef struct EEC_Connector_s {
    uint32_t id;                     /**< Unique connector id. */
    bool obsolete;                   /**< True if this object is obsolete (raises warning on use). */
    char name[32];                   /**< Connector reference label (e.g. "X1", "J1"). */
    char part_number[64];            /**< Manufacturer part number. */
    EEC_ConnectorFamily_t family;    /**< Connector housing family / manufacturer. */
    EEC_ConnectorGender_t gender;    /**< Plug gender. */
    uint8_t total_cavities;          /**< Total number of pin cavities in the housing. */
    uint8_t used_cavities;           /**< Number of cavities currently populated. */
    uint32_t max_pin_number;         /**< Highest physical pin/cavity number in this connector. */
    bool sealed;                     /**< True when the connector is sealed / waterproof. */
    char color[16];                  /**< Housing color label. */
    char mounting[32];               /**< Mounting style (panel, inline, PCB, bulkhead). */
    float rated_voltage;             /**< Maximum rated voltage (V). */
    float rated_current;             /**< Maximum rated current per contact (A). */
    char ip_rating[8];               /**< Ingress protection rating (e.g. "IP67"). */
    float temperature_min;           /**< Minimum operating temperature (deg C). */
    float temperature_max;           /**< Maximum operating temperature (deg C). */
} EEC_Connector_t;

/** @brief One sensor belonging to a system. */
typedef struct EEC_Sensor_s {
    uint32_t id;                                /**< Unique device id. */
    uint8_t variant_id;                         /**< Variant byte (0=base). Only Sensor may have >0. */
    bool obsolete;                              /**< True if this object is obsolete (raises warning on use). */
    bool is_mandatory;                          /**< True if always present on the vehicle. */
    bool mapping_enabled;                       /**< False = skip this device during auto-mapping. */
    char name[64];                              /**< Sensor name. */
    char part_number[64];                       /**< AGCO part number (alphanumeric). */
    char supplier_pn[64];                       /**< Supplier part number (alphanumeric). */
    EEC_ObjectPriority_t priority;               /**< Relative urgency assigned to the sensor. */
    EEC_SafetyClass_t safety;                    /**< Safety classification of the sensor. */
    struct EEC_System_s *owner_system;           /**< Parent system. */
    struct EEC_Architecture_s *owner_architecture; /**< Parent architecture. */
    EEC_DevicePin_t *pins;                       /**< Dynamic array of device pins. */
    uint32_t pin_count;                         /**< Number of used device pins. */
    uint32_t pin_capacity;                      /**< Allocated device pin capacity. */
    EEC_Connector_t *connectors;                 /**< Dynamic array of connectors. */
    uint32_t connector_count;                   /**< Number of connectors on this sensor. */
    uint32_t connector_capacity;                /**< Allocated connector capacity. */
} EEC_Sensor_t;

/** @brief One actuator belonging to a system. */
typedef struct EEC_Actuator_s {
    uint32_t id;                                /**< Unique device id. */
    uint8_t variant_id;                         /**< Variant byte (0=base). Only Actuator may have >0. */
    bool obsolete;                              /**< True if this object is obsolete (raises warning on use). */
    bool is_mandatory;                          /**< True if always present on the vehicle. */
    bool mapping_enabled;                       /**< False = skip this device during auto-mapping. */
    char name[64];                              /**< Actuator name. */
    char part_number[64];                       /**< AGCO part number (alphanumeric). */
    char supplier_pn[64];                       /**< Supplier part number (alphanumeric). */
    EEC_ObjectPriority_t priority;               /**< Relative urgency assigned to the actuator. */
    EEC_SafetyClass_t safety;                    /**< Safety classification of the actuator. */
    struct EEC_System_s *owner_system;           /**< Parent system. */
    struct EEC_Architecture_s *owner_architecture; /**< Parent architecture. */
    EEC_DevicePin_t *pins;                       /**< Dynamic array of device pins. */
    uint32_t pin_count;                         /**< Number of used device pins. */
    uint32_t pin_capacity;                      /**< Allocated device pin capacity. */
    EEC_Connector_t *connectors;                 /**< Dynamic array of connectors. */
    uint32_t connector_count;                   /**< Number of connectors on this actuator. */
    uint32_t connector_capacity;                /**< Allocated connector capacity. */
} EEC_Actuator_t;

/** @brief One component belonging to a system.
 *  A component groups sensors and actuators that together form a functional unit.
 *  Components can have variants (identified by variant_id in the ID).
 */
typedef struct EEC_Component_s {
    uint32_t id;                                /**< Unique component id. */
    uint8_t variant_id;                         /**< Variant byte (0=base). */
    bool obsolete;                              /**< True if this object is obsolete (raises warning on use). */
    char name[64];                              /**< Component name. */
    char part_number[64];                       /**< AGCO part number. */
    char supplier_pn[64];                       /**< Supplier part number. */
    char ref_2x[26];                            /**< Ref-2X identifier string. */
    char description[128];                      /**< Short functional description. */
    char supplier[64];                          /**< Supplier company name. */
    char location[64];                          /**< Physical zone on vehicle. */
    float take_rate;                            /**< Take rate percentage (0.0–100.0). */
    bool is_mandatory;                          /**< True if always present. */
    float weight_kg;                            /**< Component weight (kg). */
    float cost_eur;                             /**< Unit cost (EUR). */
    EEC_ObjectPriority_t priority;               /**< Relative urgency. */
    EEC_SafetyClass_t safety;                    /**< Safety classification. */
    struct EEC_System_s *owner_system;           /**< Parent system. */
    struct EEC_Architecture_s *owner_architecture; /**< Parent architecture. */
    EEC_Sensor_t **sensors;                      /**< Dynamic array of sensor pointers. */
    uint32_t sensor_count;                      /**< Number of sensors in this component. */
    uint32_t sensor_capacity;                   /**< Allocated sensor capacity. */
    EEC_Actuator_t **actuators;                  /**< Dynamic array of actuator pointers. */
    uint32_t actuator_count;                    /**< Number of actuators in this component. */
    uint32_t actuator_capacity;                 /**< Allocated actuator capacity. */
} EEC_Component_t;

/** @brief One system grouping components. */
typedef struct EEC_System_s {
    uint32_t id;                                /**< Unique system id. */
    uint8_t variant_id;                         /**< Variant byte (0=base). Only System may have >0. */
    bool obsolete;                              /**< True if this object is obsolete (raises warning on use). */
    char name[64];                              /**< System name. */
    char part_number[64];                       /**< Manufacturer or reference part number. */
    char ref_2x[26];                            /**< Ref-2X identifier string (max 25 chars). */
    float take_rate;                            /**< Take rate in percentage (0.0 to 100.0). */
    bool is_mandatory;                          /**< True if mandatory system, false if optional. */
    bool auto_mapping_enabled;                  /**< False = skip this system during auto-mapping. */
    EEC_SystemLevel_t system_level;              /**< System-level classification such as SL2. */
    EEC_ObjectPriority_t priority;               /**< Relative urgency assigned to the system. */
    EEC_SafetyClass_t safety;                    /**< Safety classification of the system. */
    char location[64];                          /**< Physical zone: Cabin, Chassis, Engine, Implement, etc. */
    struct EEC_Zone_s *zone;                     /**< Assigned zone (NULL = unassigned). Not owned. */
    struct EEC_Architecture_s *owner_architecture; /**< Parent architecture. */
    EEC_Component_t **components;                /**< Dynamic array of component pointers. */
    uint32_t component_count;                   /**< Number of components in this system. */
    uint32_t component_capacity;                /**< Allocated component capacity. */

    /* ── Platform & brand applicability ── */
    char platforms[EEC_SYSTEM_MAX_PLATFORMS][32]; /**< Platform names this system is mounted on. */
    uint32_t platform_count;                    /**< Number of assigned platforms. */
    EEC_Brand_t brands[EEC_SYSTEM_MAX_BRANDS];   /**< Brands this system applies to. */
    uint32_t brand_count;                       /**< Number of assigned brands. */

    /* ── Software components (owned) ──
     * One system owns 1..n SWCs. Each SWC is allocated to one ECU, so a
     * system whose signals are split across several ECUs uses one SWC per ECU. */
    EEC_Swc_t **swcs;                            /**< Dynamic array of owned SWC pointers. */
    uint32_t swc_count;                         /**< Number of SWCs. */
    uint32_t swc_capacity;                      /**< Allocated SWC capacity. */
} EEC_System_t;

/** @brief One physical ECU pin used by the pinout exports. */
typedef struct EEC_EcuPin_s {
    uint32_t id;                  /**< Unique ECU pin id. */
    bool obsolete;                /**< True if this object is obsolete (raises warning on use). */
    uint32_t physical_number;     /**< Physical cavity number inside the connector. */
    char connector_name[16];      /**< Connector reference, for example X1, X2, X1000. */
    char name[64];                /**< Physical pin name shown in pinout HTML. */
    char main_group[32];          /**< Main I/O group. */
    char electrical[160];         /**< Pre-filled electrical description. */
    char sw_config[160];          /**< Pre-filled software configuration keywords. */
    EEC_PinRole_t role;            /**< Physical pin role. */
    EEC_PinInterface_t interface_type; /**< Preferred electrical/communication interface for this ECU pin. */
    uint32_t supported_capability_mask;  /**< Capability mask used for automatic signal matching. */
    uint32_t diagnostic_flags;    /**< Supported diagnostic flags. */
    uint32_t electrical_capability; /**< Bitmask of EEC_ElectricalFlag_t the pin provides. */
    bool is_occupied;             /**< True when a signal is mapped (not used for GROUND pins). */
    uint32_t gnd_connect_count;   /**< Number of device GND signals sharing this pin. */
    EEC_Signal_t *connected_signal;/**< Signal currently mapped on this pin (last for GROUND). */
    char device_pin_name[64];     /**< Device-side pin name copied by the software. */
    char device_pin_desc[128];    /**< Device-side description copied by the software. */
    char **functions;             /**< Dynamic array of alternative functions/groups. */
    uint32_t function_count;      /**< Number of alternative functions. */
    uint32_t function_capacity;   /**< Allocated alternative function capacity. */
    /** Maximum AgPL level this physical pin can safely support. Defaults to E (no restriction). */
    EEC_AgplLevel_t max_agpl;
    /* ── Pre-wiring validation fields ── */
    float current_max;            /**< Maximum continuous current the pin can source/sink (A). 0 = unlimited. */
    /* Supply information provided by this ECU pin (when role == SUPPLY). */
    EEC_SensorSupplyType_t provided_sensor_supply; /**< Named supply output provided by the ECU, or generic/unknown. */
    EEC_SensorGroundType_t provided_sensor_ground; /**< Ground/return provided by this pin. */
    float provided_supply_voltage; /**< Nominal supplied voltage (V), 0 = unspecified. */
    EEC_GroundClass_t ground_class; /**< Ground classification: POWER or LOGIC. */
    EEC_ResetState_t reset_state;   /**< Actual output state at reset/power-on. */
} EEC_EcuPin_t;

/** @brief One ECU object containing physical pins and CAN addresses. */
typedef struct EEC_Ecu_s {
    uint32_t id;                                /**< Unique ECU id. */
    uint8_t variant_id;                         /**< Variant byte (0=base). Only ECU may have >0. */
    bool obsolete;                              /**< True if this object is obsolete (raises warning on use). */
    char name[64];                              /**< ECU name. */
    char part_number[64];                       /**< Manufacturer or reference part number. */
    char variant[16];                           /**< Design variant: SMALL / MEDIUM / LARGE. */
    EEC_ObjectPriority_t priority;               /**< Relative urgency assigned to the ECU. */
    EEC_SafetyClass_t safety;                    /**< Safety classification of the ECU. */
    char location[64];                          /**< Physical zone: Cabin, Chassis, Engine, Implement, etc. */
    uint8_t can_addresses[EEC_ECU_MAX_CAN_ADDRESSES]; /**< Stored CAN node addresses. */
    uint8_t can_address_count;                  /**< Number of valid CAN addresses. */
    struct EEC_Architecture_s *owner_architecture; /**< Parent architecture. */
    EEC_EcuPin_t *pins;                          /**< Dynamic array of physical pins. */
    uint32_t pin_count;                         /**< Number of physical pins. */
    uint32_t pin_capacity;                      /**< Allocated physical pin capacity. */
    EEC_Connector_t *connectors;                 /**< Dynamic array of connectors on this ECU. */
    uint32_t connector_count;                   /**< Number of connectors on this ECU. */
    uint32_t connector_capacity;                /**< Allocated connector capacity. */

    /* ── Hosted SWCs (DERIVED) ──
     * Not authoritative: rebuilt from every SWC whose allocated_ecu == this ECU
     * via EEC_Architecture_RebuildHostedSwcs(). Never populated by hand. */
    EEC_Swc_t **hosted_swcs;                     /**< Derived array of hosted SWC pointers. */
    uint32_t hosted_swc_count;                  /**< Number of hosted SWCs. */
    uint32_t hosted_swc_capacity;               /**< Allocated hosted SWC capacity. */
} EEC_Ecu_t;

/** @brief One node (ECU + port index) on a bus. */
typedef struct EEC_BusNode_s {
    EEC_Ecu_t *ecu;                              /**< Connected ECU. */
    uint8_t   port_index;                       /**< 1-based port (CAN1=1, ETH1=1, etc.). */
} EEC_BusNode_t;

/** @brief One communication bus. */
typedef struct EEC_Bus_s {
    uint32_t id;                                /**< Unique bus id. */
    bool obsolete;                              /**< True if this object is obsolete (raises warning on use). */
    char name[64];                              /**< Bus name (e.g. "Vehicle_CAN"). */
    char part_number[64];                       /**< Manufacturer or reference part number. */
    char ref_2x[26];                            /**< Ref-2X identifier string (max 25 chars). */
    EEC_BusType_t type;                          /**< Bus communication type. */
    uint32_t bitrate;                           /**< Nominal bitrate in bps. */
    EEC_ObjectPriority_t priority;               /**< Relative urgency. */
    EEC_SafetyClass_t safety;                    /**< Safety classification. */
    struct EEC_Architecture_s *owner_architecture; /**< Parent architecture. */

    EEC_BusNode_t *nodes;                        /**< Dynamic array of connected ECU+port nodes. */
    uint32_t node_count;                        /**< Number of connected nodes. */
    uint32_t node_capacity;                     /**< Allocated node capacity. */

    EEC_Signal_t **signals;                      /**< Dynamic array of routed signals. */
    uint32_t signal_count;                      /**< Number of routed signals. */
    uint32_t signal_capacity;                   /**< Allocated signal capacity. */

    /* ── CAN messages on this bus (DERIVED) ──
     * Not authoritative: rebuilt from every message that has a tx port on this
     * bus via EEC_Architecture_RebuildBusMessages(). Used for per-bus DBC export. */
    EEC_Message_t **messages;                    /**< Derived array of message pointers. */
    uint32_t message_count;                     /**< Number of messages on this bus. */
    uint32_t message_capacity;                  /**< Allocated message capacity. */
} EEC_Bus_t;

/** @brief Placement of one logical signal inside a CAN frame.
 *  Wraps an existing architecture signal and adds the on-the-wire layout that
 *  only makes sense inside a message (start bit, length, byte order, scaling). */
typedef struct EEC_MessageSignal_s {
    EEC_Signal_t *signal;                        /**< Reference to the logical signal (not owned). */
    uint16_t start_bit;                          /**< Start bit position in the frame. */
    uint16_t length;                             /**< Signal length in bits. */
    bool     little_endian;                      /**< True = Intel byte order, false = Motorola. */
    float    scale;                              /**< DBC scale factor. */
    float    offset;                             /**< DBC offset. */
    EEC_Ecu_t *receivers[EEC_MSG_MAX_RX];        /**< Receiving ECU nodes (Rx). */
    uint8_t   receiver_count;                    /**< Number of receivers. */
} EEC_MessageSignal_t;

/** @brief One transmit binding of a message: an ECU CAN port on a given bus.
 *  A message may have several tx bindings, so the same frame can be broadcast
 *  on several of the sending ECU's ports and therefore on several buses.
 *  (bus, ecu, port_index) are stable identifiers rather than a pointer into a
 *  reallocatable bus node array. */
typedef struct EEC_MessageTx_s {
    EEC_Bus_t *bus;                              /**< Bus this port transmits on. */
    EEC_Ecu_t *ecu;                              /**< ECU owning the CAN port (== owner_swc->allocated_ecu). */
    uint8_t    port_index;                       /**< CAN channel index (1-based). */
    uint32_t   cycle_time_ms;                    /**< Periodicity on this bus (0 = event-driven). */
} EEC_MessageTx_t;

/** @brief One CAN message (frame) produced by a SWC.
 *  Owned by the SWC (hence by the system): moving the SWC to another ECU moves
 *  its messages with it. Transport bindings (tx_ports) are recomputed at mapping. */
typedef struct EEC_Message_s {
    uint32_t id;                                 /**< Unique message id. */
    bool     obsolete;                           /**< True if obsolete (warns on use). */
    char     name[64];                           /**< Message name (DBC BO_). */
    uint32_t frame_id;                           /**< CAN identifier (11 or 29 bit). */
    bool     is_extended;                        /**< True = 29-bit (J1939), false = 11-bit. */
    uint32_t pgn;                                /**< J1939 PGN, auto-derived from frame_id by
                                                        EEC_Swc_CreateMessage() for extended (29-bit)
                                                        messages (see EEC_J1939_PgnFromFrameId());
                                                        0 for standard 11-bit messages. */
    uint8_t  dlc;                                /**< Data length code in bytes. */
    EEC_ObjectPriority_t priority;               /**< Relative urgency. */
    EEC_SafetyClass_t    safety;                 /**< Safety classification. */
    struct EEC_Swc_s *owner_swc;                 /**< Owning SWC (back-reference). */

    EEC_MessageTx_t *tx_ports;                   /**< Dynamic array of tx bindings (1..n). */
    uint32_t tx_count;                          /**< Number of tx bindings. */
    uint32_t tx_capacity;                       /**< Allocated tx capacity. */

    EEC_MessageSignal_t *entries;                /**< Dynamic array of signal placements. */
    uint32_t entry_count;                       /**< Number of signal placements. */
    uint32_t entry_capacity;                    /**< Allocated entry capacity. */
} EEC_Message_t;

/** @brief Software component: the logical/software behaviour of a system,
 *  allocated to exactly one ECU. Owns the CAN messages it produces. */
typedef struct EEC_Swc_s {
    uint32_t id;                                 /**< Unique runtime SWC id. */
    bool     obsolete;                           /**< True if obsolete (warns on use). */
    char     name[64];                           /**< SWC name. */
    char     ref_2x[26];                         /**< Stable SWC Ref-2X identifier (own; not the system's). */
    struct EEC_System_s *owner_system;           /**< Owning system. */
    struct EEC_Architecture_s *owner_architecture; /**< Owning architecture. */
    EEC_Ecu_t *allocated_ecu;                    /**< ECU this SWC runs on (NULL = unallocated). */

    EEC_Message_t **messages;                    /**< Dynamic array of owned messages (0..n). */
    uint32_t message_count;                     /**< Number of messages. */
    uint32_t message_capacity;                  /**< Allocated message capacity. */

    /* Software variables produced internally by this SWC. These reference
     * signals registered in arch->signals (not owned here); any of them may be
     * packed into a CAN message even without a physical device pin. */
    EEC_Signal_t **variables;                    /**< Dynamic array of produced signal pointers. */
    uint32_t variable_count;                    /**< Number of software variables. */
    uint32_t variable_capacity;                 /**< Allocated variable capacity. */
} EEC_Swc_t;

/** @brief Architecture distribution mode. */
typedef enum EEC_ArchMode_e {
    EEC_ARCH_MODE_CENTRAL = 0, /**< Systems routed across all ECUs (default). */
    EEC_ARCH_MODE_ZONAL        /**< Systems routed only to their assigned zone's ECUs. */
} EEC_ArchMode_t;

/** @brief A physical/functional zone grouping a subset of ECUs.
 *  Systems assigned to a zone are, in ZONAL mode, mapped only onto that zone's ECUs. */
typedef struct EEC_Zone_s {
    uint32_t id;                                 /**< Unique zone id. */
    char name[64];                               /**< Zone name (e.g. "Cabin", "Powertrain"). */
    struct EEC_Architecture_s *owner_architecture; /**< Parent architecture. */
    EEC_Ecu_t **ecus;                            /**< ECUs in this zone (referenced, not owned). */
    uint32_t ecu_count;                          /**< Number of ECUs in the zone. */
    uint32_t ecu_capacity;                       /**< Allocated ECU pointer capacity. */
} EEC_Zone_t;

/** @brief Top-level architecture container. */
typedef struct EEC_Architecture_s {
    uint32_t id;               /**< Architecture id. */
    bool obsolete;             /**< True if this object is obsolete (raises warning on use). */
    char name[128];            /**< Architecture name used in exports. */
    char part_number[64];      /**< Manufacturer or reference part number. */
    EEC_ObjectPriority_t priority; /**< Relative urgency assigned to the architecture. */
    EEC_SafetyClass_t safety;   /**< Safety classification of the architecture. */
    EEC_IdContext_t ids;        /**< Auto-ID generator state. */

    EEC_Signal_t **signals;     /**< Dynamic array of all architecture signals. */
    uint32_t signal_count;     /**< Number of registered signals. */
    uint32_t signal_capacity;  /**< Allocated signal pointer capacity. */

    EEC_System_t **systems;     /**< Dynamic array of all systems. */
    uint32_t system_count;     /**< Number of registered systems. */
    uint32_t system_capacity;  /**< Allocated system pointer capacity. */

    EEC_Ecu_t **ecus;           /**< Dynamic array of all ECUs. */
    uint32_t ecu_count;        /**< Number of registered ECUs. */
    uint32_t ecu_capacity;     /**< Allocated ECU pointer capacity. */

    EEC_Bus_t **buses;          /**< Dynamic array of all buses. */
    uint32_t bus_count;        /**< Number of registered buses. */
    uint32_t bus_capacity;     /**< Allocated bus pointer capacity. */

    EEC_ArchMode_t mode;        /**< Distribution mode (CENTRAL default, or ZONAL). */
    EEC_Zone_t **zones;         /**< Dynamic array of zones. */
    uint32_t zone_count;       /**< Number of registered zones. */
    uint32_t zone_capacity;    /**< Allocated zone pointer capacity. */
} EEC_Architecture_t;

/** @brief Allocate and initialize a new top-level architecture container.
 *  @param name Human-readable architecture name, or NULL to use a default name.
 *  @return Newly allocated architecture instance, or NULL on allocation failure.
 */
EEC_Architecture_t *EEC_Architecture_Create(const char *name);

/** @brief Release an architecture and every object registered below it.
 *  @param arch Architecture to destroy. NULL is accepted.
 */
void EEC_Architecture_Destroy(EEC_Architecture_t *arch);

/** @brief Replace the exported name of an existing architecture.
 *  @param arch Architecture to update.
 *  @param name New display name to copy.
 */
void EEC_Architecture_SetName(EEC_Architecture_t *arch, const char *name);

/** @brief Create and register one logical signal in the architecture.
 *  @param arch Owning architecture.
 *  @param name Signal name used in reports and exports.
 *  @param type Payload representation carried by the signal.
 *  @param interface_type Electrical or communication interface used for routing.
 *  @param unit Engineering unit associated with the signal value.
 *  @param min_value Minimum engineering value.
 *  @param max_value Maximum engineering value.
 *  @param resolution Resolution or least significant bit in engineering units.
 *  @param scaling Scaling factor applied by downstream tooling.
 *  @return Newly created signal, or NULL on invalid input or allocation failure.
 */
EEC_Signal_t *EEC_Architecture_CreateSignalEx(
    EEC_Architecture_t *arch,
    const char *name,
    EEC_SignalType_t type,
    EEC_SignalInterface_t interface_type,
    EEC_SignalUnit_t unit,
    float min_value,
    float max_value,
    float resolution,
    float scaling
);

/** @brief Create and register one system inside the architecture.
 *  @param arch Owning architecture.
 *  @param name System name.
 *  @return Newly created system, or NULL on invalid input or allocation failure.
 */
EEC_System_t *EEC_Architecture_CreateSystem(EEC_Architecture_t *arch, const char *name);

/** @brief Create and register one component inside a system.
 *  @param system Owning system.
 *  @param name Component name.
 *  @return Newly created component, or NULL on invalid input or allocation failure.
 */
EEC_Component_t *EEC_System_CreateComponent(EEC_System_t *system, const char *name);

/** @brief Create and register one sensor inside a component.
 *  @param component Owning component.
 *  @param name Sensor name.
 *  @return Newly created sensor, or NULL on invalid input or allocation failure.
 */
EEC_Sensor_t *EEC_Component_CreateSensor(EEC_Component_t *component, const char *name);

/** @brief Create and register one actuator inside a component.
 *  @param component Owning component.
 *  @param name Actuator name.
 *  @return Newly created actuator, or NULL on invalid input or allocation failure.
 */
EEC_Actuator_t *EEC_Component_CreateActuator(EEC_Component_t *component, const char *name);

/** @brief Backward-compatible wrapper: create a sensor on the system's default component.
 *  @param system Owning system.
 *  @param name Sensor name.
 *  @return Newly created sensor, or NULL on failure.
 */
EEC_Sensor_t *EEC_System_CreateSensor(EEC_System_t *system, const char *name);

/** @brief Backward-compatible wrapper: create an actuator on the system's default component.
 *  @param system Owning system.
 *  @param name Actuator name.
 *  @return Newly created actuator, or NULL on failure.
 */
EEC_Actuator_t *EEC_System_CreateActuator(EEC_System_t *system, const char *name);

/** @brief Add a platform name to a system.
 *  @param system System to update.
 *  @param platform Platform name (e.g. "MF8S", "Fendt900", "Valtra_T").
 *  @return true on success, false if full or duplicate.
 */
bool EEC_System_AddPlatform(EEC_System_t *system, const char *platform);

/** @brief Add a brand to a system.
 *  @param system System to update.
 *  @param brand Brand enum value.
 *  @return true on success, false if full or duplicate.
 */
bool EEC_System_AddBrand(EEC_System_t *system, EEC_Brand_t brand);

/** @brief Get all platforms where a system is mounted.
 *  @param system System to query.
 *  @param[out] out_platforms Caller-provided array of char[32] to receive platform names.
 *  @param max_count Maximum number of entries the caller array can hold.
 *  @return Number of platforms copied into out_platforms.
 */
uint32_t EEC_System_GetPlatforms(const EEC_System_t *system, char out_platforms[][32], uint32_t max_count);

/** @brief Get all brands where a system is mounted.
 *  @param system System to query.
 *  @param[out] out_brands Caller-provided array to receive brand values.
 *  @param max_count Maximum number of entries the caller array can hold.
 *  @return Number of brands copied into out_brands.
 */
uint32_t EEC_System_GetBrands(const EEC_System_t *system, EEC_Brand_t *out_brands, uint32_t max_count);

/** @brief Print a summary of platforms and brands for a system to the log.
 *  @param system System to report on.
 */
void EEC_System_PrintApplicability(const EEC_System_t *system);

/** @brief Convert a brand enum value to a display string.
 *  @param brand Brand to convert.
 *  @return Constant string ("Fendt", "Massey Ferguson", "Valtra").
 */
const char *EEC_Brand_ToString(EEC_Brand_t brand);

/** @brief Append one logical pin to a sensor.
 *  @param sensor Owning sensor.
 *  @param number Device-local pin number.
 *  @param role Logical direction or supply role.
 *  @param signal Logical signal carried by this device pin, or NULL.
 *  @param name Optional device-side pin name.
 *  @return Newly created device pin, or NULL on invalid input or allocation failure.
 */
EEC_DevicePin_t *EEC_Sensor_CreatePin(EEC_Sensor_t *sensor, uint32_t number, EEC_PinRole_t role, EEC_Signal_t *signal, EEC_PinInterface_t interface_type, const char *name);

/** @brief Append one logical pin to an actuator.
 *  @param actuator Owning actuator.
 *  @param number Device-local pin number.
 *  @param role Logical direction or supply role.
 *  @param signal Logical signal carried by this device pin, or NULL.
 *  @param name Optional device-side pin name.
 *  @return Newly created device pin, or NULL on invalid input or allocation failure.
 */
EEC_DevicePin_t *EEC_Actuator_CreatePin(EEC_Actuator_t *actuator, uint32_t number, EEC_PinRole_t role, EEC_Signal_t *signal, EEC_PinInterface_t interface_type, const char *name);

/* ── Connector API ───────────────────────────────────────────────────── */

/** @brief Append one physical connector housing to a sensor.
 *  @param sensor    Owning sensor.
 *  @param name      Connector reference label (e.g. "J1").
 *  @param part_number Manufacturer part number, or NULL.
 *  @param family    Connector housing family.
 *  @param gender    Plug gender.
 *  @param total_cavities Total number of pin cavities.
 *  @return Newly created connector, or NULL on invalid input or allocation failure.
 */
EEC_Connector_t *EEC_Sensor_CreateConnector(
    EEC_Sensor_t *sensor,
    const char *name,
    const char *part_number,
    EEC_ConnectorFamily_t family,
    EEC_ConnectorGender_t gender,
    uint8_t total_cavities
);

/** @brief Append one physical connector housing to an actuator.
 *  @param actuator  Owning actuator.
 *  @param name      Connector reference label.
 *  @param part_number Manufacturer part number, or NULL.
 *  @param family    Connector housing family.
 *  @param gender    Plug gender.
 *  @param total_cavities Total number of pin cavities.
 *  @return Newly created connector, or NULL on invalid input or allocation failure.
 */
EEC_Connector_t *EEC_Actuator_CreateConnector(
    EEC_Actuator_t *actuator,
    const char *name,
    const char *part_number,
    EEC_ConnectorFamily_t family,
    EEC_ConnectorGender_t gender,
    uint8_t total_cavities
);

/** @brief Append one physical connector housing to an ECU.
 *  @param ecu       Owning ECU.
 *  @param name      Connector reference label (e.g. "X1", "X2").
 *  @param part_number Manufacturer part number, or NULL.
 *  @param family    Connector housing family.
 *  @param gender    Plug gender.
 *  @param total_cavities Total number of pin cavities.
 *  @return Newly created connector, or NULL on invalid input or allocation failure.
 */
EEC_Connector_t *EEC_Ecu_CreateConnector(
    EEC_Ecu_t *ecu,
    const char *name,
    const char *part_number,
    EEC_ConnectorFamily_t family,
    EEC_ConnectorGender_t gender,
    uint8_t total_cavities
);

/** @brief Create and register one ECU shell in the architecture.
 *  @param arch Owning architecture.
 *  @param name ECU name.
 *  @param variant Variant label such as SMALL, MEDIUM, or LARGE.
 *  @return Newly created ECU, or NULL on invalid input or allocation failure.
 */
EEC_Ecu_t *EEC_Architecture_CreateEcu(EEC_Architecture_t *arch, const char *name, const char *variant);

/** @brief Append one physical pin definition to an ECU.
 *  @param ecu Owning ECU.
 *  @param physical_number Physical cavity number inside the connector.
 *  @param connector_name Connector reference name.
 *  @param name Physical pin label.
 *  @param main_group Primary I/O group or function family.
 *  @param role Physical direction or supply role.
 *  @param supported_capability_mask Capability mask accepted by the pin.
 *  @param diagnostic_flags Diagnostic features supported by the pin.
 *  @param electrical Human-readable electrical description.
 *  @param sw_config Pipe-separated software configuration hints.
 *  @return Newly created ECU pin, or NULL on invalid input or allocation failure.
 */
EEC_EcuPin_t *EEC_Ecu_CreatePin(
    EEC_Ecu_t *ecu,
    uint32_t physical_number,
    const char *connector_name,
    const char *name,
    const char *main_group,
    EEC_PinRole_t role,
    EEC_PinInterface_t interface_type,
    uint32_t supported_capability_mask,
    uint32_t diagnostic_flags,
    const char *electrical,
    const char *sw_config
);

/** @brief Add one alternative function tag to an ECU pin.
 *  @param pin Pin to update.
 *  @param function_name Function tag to append.
 *  @return true on success, false on invalid input or allocation failure.
 */
bool EEC_EcuPin_AddFunction(EEC_EcuPin_t *pin, const char *function_name);

/** @brief Store one CAN node address on an ECU.
 *  @param ecu ECU to update.
 *  @param address CAN node address to append.
 *  @return true when the address was added, false on duplicates, overflow, or invalid input.
 */
bool EEC_Ecu_AddCanAddress(EEC_Ecu_t *ecu, uint8_t address);

/** @brief Check whether an ECU already owns a CAN node address.
 *  @param ecu ECU to inspect.
 *  @param address CAN node address to search for.
 *  @return true when the ECU contains the address, false otherwise.
 */
bool EEC_Ecu_HasCanAddress(const EEC_Ecu_t *ecu, uint8_t address);

/** @brief Find one ECU pin by connector name and physical cavity number.
 *  @param ecu ECU to search.
 *  @param connector_name Connector reference name.
 *  @param physical_number Physical cavity number.
 *  @return Matching ECU pin, or NULL when no match exists.
 */
EEC_EcuPin_t *EEC_Ecu_FindPin(EEC_Ecu_t *ecu, const char *connector_name, uint32_t physical_number);

/** @brief Test whether an ECU pin can accept a given signal.
 *  @param pin Physical pin candidate.
 *  @param signal Logical signal to evaluate.
 *  @return true when the pin is free and supports the signal interface.
 */
bool EEC_Ecu_IsPinCompatible(const EEC_EcuPin_t *pin, const EEC_Signal_t *signal);

/** @brief Connect one logical signal to a specific ECU pin.
 *  @param ecu ECU containing the target pin.
 *  @param connector_name Connector reference name.
 *  @param physical_number Physical cavity number.
 *  @param signal Logical signal to map onto the pin.
 *  @return true on success, false when the pin is missing or incompatible.
 */
bool EEC_Ecu_ConnectSignalToPin(EEC_Ecu_t *ecu, const char *connector_name, uint32_t physical_number, EEC_Signal_t *signal);

/* ── Bus API ─────────────────────────────────────────────────────────── */

/** @brief Create and register one communication bus in the architecture.
 *  @param arch Owning architecture.
 *  @param name Bus name.
 *  @param type Communication protocol.
 *  @return Newly created bus, or NULL on invalid input or allocation failure.
 */
EEC_Bus_t *EEC_Architecture_CreateBus(EEC_Architecture_t *arch, const char *name, EEC_BusType_t type);

/** @brief Connect a specific communication port of an ECU to a bus.
 *  @param bus  Target bus.
 *  @param ecu  ECU to connect.
 *  @param port_index 1-based port index (CAN1=1, CAN2=2, ETH1=1, etc.).
 *  @return 0 on success, -1 on invalid input, -2 if the port is already on another bus,
 *          -3 if the ECU+port is already on this bus.
 */
int EEC_Bus_ConnectEcu(EEC_Bus_t *bus, EEC_Ecu_t *ecu, uint8_t port_index);

/** @brief Add a signal to a bus.
 *  @param bus    Target bus.
 *  @param signal Signal to route on the bus.
 *  @return 0 on success, -1 on invalid input, -2 on interface mismatch,
 *          -3 if the signal is already on this bus.
 */
int EEC_Bus_AddSignal(EEC_Bus_t *bus, EEC_Signal_t *signal);

/** @brief Auto-connect all matching bus-type signals of a system to a bus.
 *  Scans components' sensors and actuators for signals whose interface matches the bus type.
 *  @param bus    Target bus.
 *  @param system System to scan.
 *  @return Number of signals added, or -1 on error.
 */
int EEC_Bus_ConnectSystemSignals(EEC_Bus_t *bus, const EEC_System_t *system);

/** @brief Count the number of physical CAN bus ports on an ECU.
 *  Counts differential pairs (CAN*_H / CAN*_L) in the ECU pin list.
 *  @param ecu ECU to inspect.
 *  @return Number of CAN ports (0 if no CAN pins found).
 */
uint8_t EEC_Ecu_CountCanPorts(const EEC_Ecu_t *ecu);

/** @brief Count the number of physical Ethernet ports on an ECU.
 *  @param ecu ECU to inspect.
 *  @return Number of Ethernet ports.
 */
uint8_t EEC_Ecu_CountEthernetPorts(const EEC_Ecu_t *ecu);

/** @brief Walk the architecture and emit a warning for every obsolete object in use.
 *  @param arch Architecture to audit.
 *  @return Number of warnings emitted.
 */
uint32_t EEC_Architecture_CheckObsolete(const EEC_Architecture_t *arch);

/** @brief Check whether an ECU pin can provide the power required by a device pin.
 *  @param ecu_pin  Candidate ECU pin (may be role SUPPLY).
 *  @param device_pin Device-side pin requiring supply (role SUPPLY).
 *  @return true when the ECU pin is compatible with the device supply requirements.
 */
bool EEC_Pin_SupplyCompatible(const EEC_EcuPin_t *ecu_pin, const EEC_DevicePin_t *device_pin);

#ifdef __cplusplus
}
#endif
#endif
