#!/usr/bin/env python3
"""Generate an interactive HTML system architecture diagram — fully automatic.

Reads:
  - exports/example_architecture.json  (generated by app.exe)

Everything is derived from the live exported JSON. Any change in main.c
(new system, new component, new signal) is reflected on the next build+run —
no script changes needed.

Each system row shows:
  Sensors → System → Estimated I/O Consumption → Actuators

The I/O consumption box tallies pins per interface type from the
component devices as exported by the C framework.

Usage:
    python tools/generate_logical_architecture_html.py
"""
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path
from typing import Any

from html_overflow_guard import OVERFLOW_GUARD_CSS


# ── Helpers ──────────────────────────────────────────────────────────────

def esc(v: Any) -> str:
    return str("" if v is None else v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def load_json(p: Path) -> dict[str, Any]:
    d = json.loads(p.read_text(encoding="utf-8"))
    if not isinstance(d, dict):
        raise ValueError("Top-level JSON must be an object")
    return d


def find_base() -> Path:
    script_dir = Path(__file__).resolve().parent
    if (script_dir.parent / "exports").exists():
        return script_dir.parent
    return script_dir


def get_arch(data: dict[str, Any]) -> dict[str, Any]:
    a = data.get("architecture", data)
    if not isinstance(a, dict):
        raise ValueError("architecture must be an object")
    return a


def _strip_suffix(name: str) -> str:
    """Strip trailing _NN index to get the signal prefix group, e.g. CVT130_InSpd_01 -> CVT130_InSpd."""
    return re.sub(r"_\d+$", "", name)


# ── Electrical-flag bitmask decoder ─────────────────────────────────────

_ELEC_FLAGS = [
    (0x01, "PULL-UP"),
    (0x02, "PULL-DOWN"),
    (0x04, "HIGH-SIDE"),
    (0x08, "LOW-SIDE"),
    (0x10, "PUSH-PULL"),
    (0x20, "CURR-SENSE"),
    (0x40, "VOLT-IN"),
    (0x80, "DIFF"),
]


def decode_elec(val: int) -> list[str]:
    """Return list of flag names set in val."""
    return [label for mask, label in _ELEC_FLAGS if val & mask]


# ── Interface colours (auto-extended at runtime for unknown types) ───────

_PALETTE = [
    "#3b82f6", "#f59e0b", "#8b5cf6", "#ef4444", "#f97316",
    "#06b6d4", "#10b981", "#dc2626", "#6b7280", "#ec4899",
    "#14b8a6", "#a855f7", "#84cc16", "#e11d48", "#0ea5e9",
]

_KNOWN_COLORS: dict[str, str] = {
    "DIGITAL":  "#3b82f6",
    "ANALOG":   "#f59e0b",
    "PWM":      "#8b5cf6",
    "CAN":      "#ef4444",
    "LIN":      "#f97316",
    "SENT":     "#06b6d4",
    "ETHERNET": "#10b981",
    "POWER":    "#dc2626",
    "GROUND":   "#6b7280",
}


def iface_color(name: str) -> str:
    """Return the colour for an interface type, allocating one if unknown."""
    if name not in _KNOWN_COLORS:
        idx = len(_KNOWN_COLORS) % len(_PALETTE)
        _KNOWN_COLORS[name] = _PALETTE[idx]
    return _KNOWN_COLORS[name]


# ── Data loading ─────────────────────────────────────────────────────────

def load_systems(base: Path) -> tuple[str, list[dict]]:
    """Load systems from the live exported architecture JSON.

    Returns (arch_name, systems_list) where each system dict has the same
    shape used by the rest of the rendering functions:
      {name, system_level, priority, safety,
       devices: [{name, device_type, priority, safety, signals:[
         {prefix, count, interface, type, role, unit, min, max}]}]}
    """
    json_path = base / "exports" / "example_architecture.json"
    if not json_path.exists():
        json_path = base / "exports" / "example_physical_architecture.json"
    if not json_path.exists():
        raise SystemExit(f"Missing exported JSON: {json_path}")

    arch = get_arch(load_json(json_path))
    arch_name = str(arch.get("name", "Architecture"))
    systems_raw = arch.get("systems", [])
    if not isinstance(systems_raw, list):
        return arch_name, []

    systems: list[dict] = []
    for sys in systems_raw:
        if not isinstance(sys, dict):
            continue
        devs: list[dict] = []
        for dev in sys.get("devices", []):
            if not isinstance(dev, dict):
                continue
            # Group device pins into signal groups keyed by (prefix, iface, type, role, unit, ...)
            groups: dict[tuple, dict] = {}
            for pin in dev.get("pins", []):
                if not isinstance(pin, dict):
                    continue
                sig = pin.get("signal")
                if not isinstance(sig, dict) or not sig.get("name"):
                    continue
                sname  = str(sig["name"])
                prefix = _strip_suffix(sname)
                iface  = str(sig.get("interface", "?"))
                stype  = str(sig.get("type", "?"))
                role   = str(pin.get("role", "?"))
                unit   = str(sig.get("unit", ""))
                mn     = sig.get("min", 0)
                mx     = sig.get("max", 0)
                res    = sig.get("resolution", 0)
                scale  = sig.get("scaling", 1.0)
                sprio  = str(sig.get("priority", ""))
                ssafe  = str(sig.get("safety", ""))
                elec   = int(pin.get("electrical_requirement", 0))
                key    = (prefix, iface, stype, role, unit, mn, mx, res, scale, sprio, ssafe)
                if key not in groups:
                    groups[key] = {
                        "prefix": prefix, "interface": iface, "type": stype,
                        "role": role, "unit": unit, "min": mn, "max": mx,
                        "resolution": res, "scaling": scale,
                        "signal_priority": sprio, "signal_safety": ssafe,
                        "elec_flags": set(), "count": 0,
                    }
                groups[key]["count"] += 1
                if elec:
                    groups[key]["elec_flags"].add(elec)

            # Convert elec_flags sets to sorted lists
            signal_list = []
            for g in groups.values():
                g["elec_flags"] = sorted(g["elec_flags"])
                signal_list.append(g)

            devs.append({
                "name":        str(dev.get("name", "Device")),
                "device_type": str(dev.get("type", "SENSOR")),
                "priority":    str(dev.get("priority", "")),
                "safety":      str(dev.get("safety", "")),
                "signals":     signal_list,
            })
        systems.append({
            "name":         str(sys.get("name", "System")),
            "system_level": str(sys.get("system_level", "")),
            "priority":     str(sys.get("priority", "")),
            "safety":       str(sys.get("safety", "")),
            "devices":      devs,
        })
    return arch_name, systems


# ── Signal stats ─────────────────────────────────────────────────────────

def count_signals(system: dict) -> dict:
    """Return {total, by_interface} computed from system devices."""
    by_iface: dict[str, int] = {}
    total = 0
    for dev in system.get("devices", []):
        for sig in dev.get("signals", []):
            n = sig.get("count", 1)
            iface = sig.get("interface", "?")
            by_iface[iface] = by_iface.get(iface, 0) + n
            total += n
    return {"total": total, "by_interface": by_iface}


def device_signal_count(dev: dict) -> int:
    return sum(s.get("count", 1) for s in dev.get("signals", []))


# ── HTML fragments ───────────────────────────────────────────────────────

def render_signal_row(sig: dict) -> str:
    prefix   = esc(sig.get("prefix", "?"))
    count    = sig.get("count", 1)
    iface    = sig.get("interface", "?")
    unit     = sig.get("unit", "")
    stype    = sig.get("type", "?")
    role     = sig.get("role", "?")
    lo       = sig.get("min", 0)
    hi       = sig.get("max", 0)
    res      = sig.get("resolution", 0)
    scale    = sig.get("scaling", 1.0)
    sprio    = sig.get("signal_priority", "")
    ssafe    = sig.get("signal_safety", "")
    elec_vals = sig.get("elec_flags", [])
    color    = iface_color(iface)

    # — Range / unit —
    if unit and unit not in ("NONE", "BOOLEAN", ""):
        range_str = f'<span class="sig-range">{lo}&ndash;{hi} <b>{esc(unit)}</b></span>'
    elif unit == "BOOLEAN":
        range_str = '<span class="sig-range">0&nbsp;/&nbsp;1</span>'
    else:
        range_str = ""

    # — Resolution —
    res_str = (f'<span class="sig-res" title="Resolution">&#177;{res}</span>'
               if res and res != 0 else "")

    # — Scaling —
    scale_str = (f'<span class="sig-scale" title="Scaling factor">&times;{scale}</span>'
                 if scale and scale != 1.0 else "")

    # — Signal priority badge —
    prio_colors = {"LOW": "#64748b", "MEDIUM": "#3b82f6",
                   "HIGH": "#f59e0b", "CRITICAL": "#ef4444"}
    prio_str = ""
    if sprio:
        pc = prio_colors.get(sprio.upper(), "#64748b")
        prio_str = f'<span class="sig-badge" style="background:{pc}" title="Signal priority">{esc(sprio)}</span>'

    # — Signal safety badge —
    safe_str = ""
    if ssafe:
        sc = "#ef4444" if "SAFETY" in ssafe.upper() else "#22c55e"
        safe_str = f'<span class="sig-badge sig-safe-badge" style="background:{sc}" title="Safety class">{esc(ssafe.replace("_"," "))}</span>'

    # — Electrical flags (decoded from bitmask) —
    elec_parts: list[str] = []
    for val in elec_vals:
        flags = decode_elec(val)
        if flags:
            elec_parts.append(" | ".join(flags))
    elec_str = ""
    if elec_parts:
        unique_elec = " / ".join(dict.fromkeys(elec_parts))
        elec_str = f'<span class="sig-elec" title="Electrical requirements">{esc(unique_elec)}</span>'

    role_cls = {"INPUT": "role-in", "OUTPUT": "role-out"}.get(role, "role-io")

    detail_content = res_str + scale_str + prio_str + safe_str + elec_str

    return (
        f'<div class="sig-row" data-iface="{esc(iface)}">'
        # top line: interface | name x count | type | role | range
        f'<div class="sig-main">'
        f'<span class="sig-iface" style="background:{color}">{esc(iface)}</span>'
        f'<span class="sig-name">{prefix}</span>'
        f'<span class="sig-count">&times;{count}</span>'
        f'<span class="sig-type">{esc(stype)}</span>'
        f'<span class="{role_cls}">{esc(role)}</span>'
        f'{range_str}'
        f'</div>'
        # detail line: resolution | scaling | priority | safety | elec flags
        + (f'<div class="sig-detail">{detail_content}</div>' if detail_content else "")
        + f'</div>'
    )


def render_device_block(dev: dict) -> str:
    name = esc(dev.get("name", "?"))
    dtype = dev.get("device_type", "SENSOR")
    sig_count = device_signal_count(dev)
    icon = "&#9651;" if dtype == "SENSOR" else "&#9661;"
    cls = "dev-sensor" if dtype == "SENSOR" else "dev-actuator"

    signals_html = "\n".join(render_signal_row(s) for s in dev.get("signals", []))

    return (
        f'<div class="device {cls}">'
        f'<div class="dev-header">'
        f'<span class="dev-icon">{icon}</span>'
        f'<span class="dev-name">{name}</span>'
        f'<span class="dev-count">{sig_count}</span>'
        f'</div>'
        f'<div class="sig-list">{signals_html}</div>'
        f'</div>'
    )


def render_io_estimation(stats: dict) -> str:
    """Build the Estimated I/O Consumption card from by_interface counts."""
    by_iface = stats["by_interface"]
    total = stats["total"]

    if not by_iface:
        return '<div class="io-card io-empty"><div class="io-title">No I/O</div></div>'

    max_cnt = max(by_iface.values()) if by_iface else 1

    rows = ""
    for iface in sorted(by_iface.keys()):
        cnt = by_iface[iface]
        color = iface_color(iface)
        bar_pct = round(100 * cnt / max_cnt) if max_cnt else 0
        rows += (
            f'<div class="io-row">'
            f'<span class="io-iface-dot" style="background:{color}"></span>'
            f'<span class="io-iface-label">{esc(iface)}</span>'
            f'<span class="io-bar-wrap"><span class="io-bar-fill" style="width:{bar_pct}%;background:{color}"></span></span>'
            f'<span class="io-cnt">{cnt}</span>'
            f'</div>'
        )

    return (
        f'<div class="io-card">'
        f'<div class="io-chip">I/O</div>'
        f'<div class="io-title">Estimated I/O</div>'
        f'<div class="io-subtitle">Consumption</div>'
        f'<div class="io-total">{total} pins needed</div>'
        f'<div class="io-rows">{rows}</div>'
        f'</div>'
    )


def _arrow_svg(idx: int) -> str:
    """Inline SVG right-arrow with a unique marker id per call."""
    mid = f"ah{idx}"
    return (
        f'<div class="arch-arrow">'
        f'<svg viewBox="0 0 60 40" preserveAspectRatio="none">'
        f'<defs><marker id="{mid}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto">'
        f'<path d="M0,0 L8,4 L0,8" fill="#94a3b8"/></marker></defs>'
        f'<line x1="4" y1="20" x2="52" y2="20" stroke="#94a3b8" stroke-width="2" marker-end="url(#{mid})"/>'
        f'</svg></div>'
    )


def render_system_block(system: dict, row_idx: int) -> str:
    name  = esc(system.get("name", "System"))
    level = system.get("system_level", "")
    prio  = system.get("priority", "")
    safety = system.get("safety", "")
    stats = count_signals(system)
    total = stats["total"]

    sensors   = [d for d in system.get("devices", []) if d.get("device_type") == "SENSOR"]
    actuators = [d for d in system.get("devices", []) if d.get("device_type") == "ACTUATOR"]

    # Interface summary badges
    iface_badges = ""
    for iface, cnt in sorted(stats["by_interface"].items()):
        color = iface_color(iface)
        iface_badges += f'<span class="iface-badge" style="background:{color}">{esc(iface)} {cnt}</span> '

    # Metadata badges (level / priority / safety)
    meta_badges = ""
    if level:
        meta_badges += f'<span class="iface-badge" style="background:#1d4ed8">{esc(level)}</span> '
    if prio:
        prio_colors = {"LOW":"#64748b","MEDIUM":"#3b82f6","HIGH":"#f59e0b","CRITICAL":"#ef4444"}
        pc = prio_colors.get(prio.upper(), "#64748b")
        meta_badges += f'<span class="iface-badge" style="background:{pc}">{esc(prio)}</span> '
    if safety:
        sc = "#ef4444" if "SAFETY" in safety.upper() else "#22c55e"
        meta_badges += f'<span class="iface-badge" style="background:{sc}">{esc(safety.replace("_"," "))}</span> '

    sensors_html   = "\n".join(render_device_block(d) for d in sensors)
    actuators_html = "\n".join(render_device_block(d) for d in actuators)
    io_html        = render_io_estimation(stats)

    # Arrow ids must be unique across all rows
    a1 = row_idx * 3
    a2 = a1 + 1
    a3 = a1 + 2

    return f'''<div class="arch-row" data-system="{esc(system.get("name",""))}">
  <div class="arch-col arch-sensors">
    <div class="col-title">&#9651; Sensors / Inputs</div>
    {sensors_html}
  </div>

  {_arrow_svg(a1)}

  <div class="arch-col arch-system">
    <div class="sys-block">
      <div class="sys-header">
        <span class="sys-icon">&#9638;</span> {name}
      </div>
      <div class="sys-meta">{meta_badges}</div>
      <div class="sys-stats">{total} signals (active variant)</div>
      <div class="sys-ifaces">{iface_badges}</div>
    </div>
  </div>

  {_arrow_svg(a2)}

  <div class="arch-col arch-io-col">
    <div class="col-title">&#9881; Estimated I/O Consumption</div>
    {io_html}
  </div>

  {_arrow_svg(a3)}

  <div class="arch-col arch-actuators">
    <div class="col-title">&#9661; Actuators / Outputs</div>
    {actuators_html}
  </div>
</div>'''


# ── Full page ────────────────────────────────────────────────────────────

def generate_html(arch_name: str, systems: list[dict]) -> str:
    total_signals = sum(count_signals(s)["total"] for s in systems)
    total_devices = sum(len(s.get("devices", [])) for s in systems)
    today = date.today().strftime("%d/%m/%Y")

    # Collect all interface types across all systems
    all_ifaces: dict[str, int] = {}
    for s in systems:
        for iface, cnt in count_signals(s)["by_interface"].items():
            all_ifaces[iface] = all_ifaces.get(iface, 0) + cnt

    # Render each system row
    rows_html = ""
    for idx, system in enumerate(systems):
        rows_html += render_system_block(system, idx)

    legend_html = ""
    for iface in sorted(all_ifaces.keys()):
        c = iface_color(iface)
        legend_html += (
            f'<span class="legend-item">'
            f'<span class="legend-dot" style="background:{c}"></span>'
            f'{esc(iface)} ({all_ifaces[iface]})</span>'
        )

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>System Architecture &mdash; {esc(arch_name)}</title>
<style>
:root {{
  --bg:#070b12;--card:#151e2e;--text:#cfdaea;--muted:#6c83a2;
  --border:#233149;--accent:#2ee6ff;--accent2:#5aa6ff;--radius:10px;
  --surface0:#0b1018;--surface1:#0f1622;--surface2:#151e2e;--surface3:#1d2939;
  --surface4:#273548;--border0:#1a2436;--border1:#233149;--border2:#2d3e5c;
  --text-dim:#6c83a2;--cyan:#2ee6ff;--green:#2ee6a0;--amber:#ffb43d;--red:#ff5a78;
  --purple:#b388ff;--teal:#19d6c0;--blue:#5aa6ff;
  --shadow:0 8px 30px rgba(0,0,0,.45);
}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Segoe UI',system-ui,-apple-system,sans-serif;
  background:radial-gradient(circle at top left, rgba(46,230,255,0.06), transparent 28%), var(--bg);color:var(--text);line-height:1.6;padding:28px 24px}}

/* ─── Page header ─── */
.page-hdr{{
  background:linear-gradient(135deg,var(--surface2),var(--surface3));
  color:var(--text);padding:32px 36px;border-radius:var(--radius);
  margin-bottom:24px;box-shadow:0 8px 30px rgba(0,0,0,.45);
}}
.page-hdr h1{{font-size:1.7rem;margin-bottom:4px}}
.page-hdr .sub{{opacity:.8;font-size:.92rem}}

/* ─── Stats ─── */
.stats{{display:flex;gap:14px;flex-wrap:wrap;margin-bottom:20px}}
.stat{{background:var(--surface2);border:1px solid var(--border1);border-radius:var(--radius);
  padding:14px 20px;text-align:center;min-width:130px;flex:1;
  box-shadow:0 8px 30px rgba(0,0,0,.45)}}
.stat .n{{font-size:1.8rem;font-weight:800;color:var(--accent2);display:block}}
.stat .l{{font-size:.8rem;color:var(--muted)}}

/* ─── Legend ─── */
.legend{{background:var(--surface2);border:1px solid var(--border1);border-radius:var(--radius);
  padding:12px 18px;margin-bottom:10px;display:flex;gap:16px;flex-wrap:wrap;align-items:center}}
.legend-title{{font-weight:700;font-size:.82rem;color:var(--muted)}}
.legend-item{{display:inline-flex;align-items:center;gap:5px;font-size:.82rem}}
.legend-dot{{width:11px;height:11px;border-radius:3px;display:inline-block}}

/* ─── Filter ─── */
.filter-bar{{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:24px}}
.fbtn{{border:1px solid var(--border1);background:var(--surface2);border-radius:6px;
  padding:5px 14px;font-size:.82rem;cursor:pointer;font-weight:600;color:var(--text);transition:all .15s}}
.fbtn:hover{{background:var(--accent2);color:#000;border-color:var(--accent2)}}
.fbtn.on{{background:var(--accent);color:#000;border-color:var(--accent)}}

/* ─── Architecture row (1 system = 1 horizontal band) ─── */
.arch-row{{
  display:flex;align-items:stretch;
  margin-bottom:36px;
  background:var(--surface1);border:1px solid var(--border1);
  border-radius:var(--radius);
  box-shadow:0 8px 30px rgba(0,0,0,.45);
  overflow:hidden;
}}
.arch-col{{padding:18px 16px;flex:1;min-width:0}}
.arch-sensors{{background:rgba(46,230,255,0.04);flex:2}}
.arch-actuators{{background:rgba(255,180,61,0.04);flex:2}}
.arch-system{{
  display:flex;flex-direction:column;align-items:center;
  justify-content:center;padding:24px 8px;flex:0 0 180px;
}}
.arch-io-col{{
  display:flex;flex-direction:column;align-items:center;
  justify-content:flex-start;padding:18px 10px;flex:0 0 210px;
}}
.arch-arrow{{
  display:flex;align-items:center;justify-content:center;
  flex:0 0 50px;padding:0;
}}
.arch-arrow svg{{width:50px;height:40px}}
.col-title{{
  font-size:.72rem;font-weight:700;text-transform:uppercase;
  letter-spacing:.8px;color:var(--muted);margin-bottom:10px;
}}

/* ─── System block (center) ─── */
.sys-block{{
  border:3px solid var(--accent);border-radius:var(--radius);
  padding:16px 14px;text-align:center;width:164px;
  background:linear-gradient(135deg,var(--surface2),var(--surface3));color:var(--text);
  box-shadow:0 8px 30px rgba(0,0,0,.45);
}}
.sys-header{{font-weight:700;font-size:.95rem;margin-bottom:6px}}
.sys-icon{{opacity:.6}}
.sys-meta{{display:flex;gap:3px;flex-wrap:wrap;justify-content:center;margin-bottom:5px}}
.sys-stats{{font-size:.78rem;opacity:.7;margin-bottom:6px}}
.sys-ifaces{{display:flex;gap:4px;flex-wrap:wrap;justify-content:center}}
.iface-badge{{display:inline-block;color:#fff;border-radius:8px;
  padding:1px 8px;font-size:.68rem;font-weight:600}}

/* ─── I/O Estimation card ─── */
.io-card{{
  border:3px solid var(--teal);border-radius:var(--radius);padding:14px;
  width:190px;background:var(--surface2);
}}
.io-empty{{border-color:#cbd5e1;text-align:center}}
.io-chip{{
  display:inline-block;color:#000;padding:2px 12px;border-radius:6px;
  font-size:.72rem;font-weight:700;margin-bottom:4px;
  background:var(--teal);
}}
.io-title{{font-weight:700;font-size:.92rem;color:var(--teal)}}
.io-subtitle{{font-size:.76rem;color:var(--muted);margin-bottom:6px}}
.io-total{{font-size:.78rem;font-weight:700;color:var(--text);margin-bottom:10px;
  padding:3px 0;border-bottom:1px solid var(--border1)}}
.io-rows{{text-align:left}}
.io-row{{display:flex;align-items:center;gap:5px;margin-bottom:4px}}
.io-iface-dot{{width:9px;height:9px;border-radius:3px;flex-shrink:0}}
.io-iface-label{{font-size:.74rem;font-weight:600;color:var(--muted);min-width:62px}}
.io-bar-wrap{{flex:1;height:8px;background:var(--surface3);border-radius:4px;overflow:hidden}}
.io-bar-fill{{height:100%;border-radius:4px;transition:width .4s}}
.io-cnt{{font-size:.76rem;font-weight:700;min-width:22px;text-align:right}}

/* ─── Device blocks ─── */
.device{{border:1px solid var(--border1);border-radius:8px;
  margin-bottom:10px;overflow:hidden;background:var(--surface2)}}
.dev-sensor{{border-left:4px solid #3b82f6}}
.dev-actuator{{border-left:4px solid #f59e0b}}
.dev-header{{display:flex;align-items:center;gap:6px;padding:8px 10px;
  background:var(--surface3);border-bottom:1px solid var(--border1);cursor:pointer}}
.dev-icon{{font-size:1rem;color:var(--muted)}}
.dev-name{{font-weight:700;font-size:.84rem;flex:1}}
.dev-count{{font-size:.72rem;font-weight:700;background:var(--accent2);
  color:#fff;padding:1px 8px;border-radius:8px}}

/* ─── Signal rows ─── */
.sig-list{{padding:6px 8px}}
.sig-row{{display:flex;flex-direction:column;gap:0;padding:5px 4px;
  border-radius:6px;font-size:.8rem;border-bottom:1px solid var(--border1)}}
.sig-row:last-child{{border-bottom:none}}
.sig-row:hover{{background:var(--surface3)}}
.sig-main{{display:flex;align-items:center;gap:6px;flex-wrap:wrap}}
.sig-detail{{display:flex;align-items:center;gap:5px;flex-wrap:wrap;
  padding:3px 0 2px 62px;margin-top:2px}}
.sig-iface{{color:#fff;font-size:.65rem;font-weight:700;padding:2px 8px;
  border-radius:5px;min-width:58px;text-align:center;flex-shrink:0}}
.sig-name{{font-weight:600;min-width:90px}}
.sig-count{{color:var(--muted);font-size:.76rem;min-width:30px}}
.sig-type{{font-family:'Cascadia Code',Consolas,monospace;font-size:.74rem;
  background:var(--surface3);padding:1px 6px;border-radius:4px;color:var(--text-dim);font-weight:700}}
.sig-range{{font-size:.76rem;color:var(--text-dim);background:var(--surface3);
  padding:1px 8px;border-radius:4px;border:1px solid var(--border1)}}
.sig-res{{font-size:.68rem;color:#7c3aed;background:#f3e8ff;
  padding:1px 7px;border-radius:4px;font-family:monospace}}
.sig-scale{{font-size:.68rem;color:#0891b2;background:#ecfeff;
  padding:1px 7px;border-radius:4px;font-family:monospace}}
.sig-badge{{color:#fff;font-size:.64rem;font-weight:700;
  padding:1px 8px;border-radius:8px;letter-spacing:.3px}}
.sig-safe-badge{{font-size:.63rem!important}}
.sig-elec{{font-size:.67rem;color:var(--text-dim);background:var(--surface3);
  padding:1px 8px;border-radius:4px;border:1px solid var(--border1);
  font-family:'Cascadia Code',Consolas,monospace}}
.role-in{{background:rgba(46,230,255,0.12);color:var(--cyan);font-size:.66rem;font-weight:700;
  padding:2px 8px;border-radius:5px}}
.role-out{{background:rgba(255,180,61,0.12);color:var(--amber);font-size:.66rem;font-weight:700;
  padding:2px 8px;border-radius:5px}}
.role-io{{background:rgba(179,136,255,0.12);color:var(--purple);font-size:.66rem;font-weight:700;
  padding:2px 8px;border-radius:5px}}

/* ─── Footer ─── */
.footer{{text-align:center;color:var(--muted);font-size:.82rem;
  margin-top:36px;padding-top:18px;border-top:2px solid var(--border)}}

@media print{{body{{padding:10px}}.filter-bar{{display:none}}}}
@media(max-width:1000px){{
  .arch-row{{flex-direction:column}}
  .arch-arrow svg{{transform:rotate(90deg)}}
  .arch-sensors,.arch-actuators{{border:none;border-bottom:2px dashed var(--border)}}
  .arch-system,.arch-io-col{{flex:unset}}
}}
{OVERFLOW_GUARD_CSS}
</style>
</head>
<body>

<div class="page-hdr">
  <h1>Logical System Architecture &mdash; {esc(arch_name)}</h1>
  <div class="sub">Auto-generated from example_architecture.json &mdash; reflects active variant/option devices &mdash; {today}</div>
</div>

<div class="stats">
  <div class="stat"><span class="n">{len(systems)}</span><span class="l">Systems</span></div>
  <div class="stat"><span class="n">{total_signals}</span><span class="l">Active Signals</span></div>
  <div class="stat"><span class="n">{total_devices}</span><span class="l">Active Devices</span></div>
  <div class="stat"><span class="n">{len(all_ifaces)}</span><span class="l">Interface Types</span></div>
</div>

<div class="legend">
  <span class="legend-title">Interfaces:</span>
  {legend_html}
</div>

<div class="filter-bar" id="fbar">
  <button class="fbtn on" onclick="fAll(this)">All</button>
</div>

{rows_html}

<div class="footer">
  {esc(arch_name)} &mdash; Logical System Architecture &mdash; Auto-generated {today}<br>
  {len(systems)} system(s) &bull; {total_signals} signal(s) &bull; {len(all_ifaces)} interface type(s)
</div>

<script>
// Build filter buttons
(function(){{
  var ifaces={json.dumps(sorted(all_ifaces.keys()))};
  var bar=document.getElementById('fbar');
  ifaces.forEach(function(i){{
    var b=document.createElement('button');
    b.className='fbtn';b.textContent=i;
    b.onclick=function(){{fIface(i,b)}};bar.appendChild(b);
  }});
}})();
function fAll(btn){{
  document.querySelectorAll('.sig-row').forEach(function(r){{r.style.display=''}});
  document.querySelectorAll('.fbtn').forEach(function(b){{b.classList.remove('on')}});
  btn.classList.add('on');
}}
function fIface(iface,btn){{
  document.querySelectorAll('.fbtn').forEach(function(b){{b.classList.remove('on')}});
  btn.classList.add('on');
  document.querySelectorAll('.sig-row').forEach(function(r){{
    r.style.display=r.getAttribute('data-iface')===iface?'':'none';
  }});
}}
// Collapse/expand devices
document.querySelectorAll('.dev-header').forEach(function(h){{
  h.addEventListener('click',function(){{
    var l=this.parentElement.querySelector('.sig-list');
    if(l)l.style.display=l.style.display==='none'?'':'none';
  }});
}});
</script>
</body>
</html>'''


# ── Main ─────────────────────────────────────────────────────────────────

def main() -> None:
    base = find_base()
    arch_name, systems = load_systems(base)

    if not systems:
        print("[WARN] No systems found in architecture JSON")
        return

    html = generate_html(arch_name, systems)
    out_dir = base / "exports"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / "logical_architecture.html"
    out_path.write_text(html, encoding="utf-8")

    total = sum(count_signals(s)["total"] for s in systems)
    ifaces: set[str] = set()
    for s in systems:
        ifaces.update(count_signals(s)["by_interface"].keys())
    print(f"[OK] Generated: {out_path}  ({len(systems)} systems, {total} signals, {len(ifaces)} interface types)")


if __name__ == "__main__":
    main()
